# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: daily

    - package-ecosystem: gitsubmodule
      directory: /
      schedule:
          interval: daily
# change
