run:
    go: '1.22'
    timeout: 5m
    allow-parallel-runners: true

issues:
    exclude-dirs:
        - language

linters:
    presets:
        - test
        - unused

    disable:
        - exhaustruct
