// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: enums_productinfo.proto

package steam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EContentDescriptorID int32

const (
	EContentDescriptorID_k_EContentDescriptor_NudityOrSexualContent   EContentDescriptorID = 1
	EContentDescriptorID_k_EContentDescriptor_FrequentViolenceOrGore  EContentDescriptorID = 2
	EContentDescriptorID_k_EContentDescriptor_AdultOnlySexualContent  EContentDescriptorID = 3
	EContentDescriptorID_k_EContentDescriptor_GratuitousSexualContent EContentDescriptorID = 4
	EContentDescriptorID_k_EContentDescriptor_AnyMatureContent        EContentDescriptorID = 5
	EContentDescriptorID_k_EContentDescriptorMAX                      EContentDescriptorID = 6
)

// Enum value maps for EContentDescriptorID.
var (
	EContentDescriptorID_name = map[int32]string{
		1: "k_EContentDescriptor_NudityOrSexualContent",
		2: "k_EContentDescriptor_FrequentViolenceOrGore",
		3: "k_EContentDescriptor_AdultOnlySexualContent",
		4: "k_EContentDescriptor_GratuitousSexualContent",
		5: "k_EContentDescriptor_AnyMatureContent",
		6: "k_EContentDescriptorMAX",
	}
	EContentDescriptorID_value = map[string]int32{
		"k_EContentDescriptor_NudityOrSexualContent":   1,
		"k_EContentDescriptor_FrequentViolenceOrGore":  2,
		"k_EContentDescriptor_AdultOnlySexualContent":  3,
		"k_EContentDescriptor_GratuitousSexualContent": 4,
		"k_EContentDescriptor_AnyMatureContent":        5,
		"k_EContentDescriptorMAX":                      6,
	}
)

func (x EContentDescriptorID) Enum() *EContentDescriptorID {
	p := new(EContentDescriptorID)
	*p = x
	return p
}

func (x EContentDescriptorID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EContentDescriptorID) Descriptor() protoreflect.EnumDescriptor {
	return file_enums_productinfo_proto_enumTypes[0].Descriptor()
}

func (EContentDescriptorID) Type() protoreflect.EnumType {
	return &file_enums_productinfo_proto_enumTypes[0]
}

func (x EContentDescriptorID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EContentDescriptorID) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EContentDescriptorID(num)
	return nil
}

// Deprecated: Use EContentDescriptorID.Descriptor instead.
func (EContentDescriptorID) EnumDescriptor() ([]byte, []int) {
	return file_enums_productinfo_proto_rawDescGZIP(), []int{0}
}

type EInteractiveElement int32

const (
	EInteractiveElement_k_EInteractiveElement_Invalid                          EInteractiveElement = 0
	EInteractiveElement_k_EInteractiveElement_InGamePurchases                  EInteractiveElement = 1
	EInteractiveElement_k_EInteractiveElement_InGamePurchasesOfRandomizedItems EInteractiveElement = 2
	EInteractiveElement_k_EInteractiveElement_InGameChat                       EInteractiveElement = 3
	EInteractiveElement_k_EInteractiveElement_OnlineInteractivity              EInteractiveElement = 4
)

// Enum value maps for EInteractiveElement.
var (
	EInteractiveElement_name = map[int32]string{
		0: "k_EInteractiveElement_Invalid",
		1: "k_EInteractiveElement_InGamePurchases",
		2: "k_EInteractiveElement_InGamePurchasesOfRandomizedItems",
		3: "k_EInteractiveElement_InGameChat",
		4: "k_EInteractiveElement_OnlineInteractivity",
	}
	EInteractiveElement_value = map[string]int32{
		"k_EInteractiveElement_Invalid":                          0,
		"k_EInteractiveElement_InGamePurchases":                  1,
		"k_EInteractiveElement_InGamePurchasesOfRandomizedItems": 2,
		"k_EInteractiveElement_InGameChat":                       3,
		"k_EInteractiveElement_OnlineInteractivity":              4,
	}
)

func (x EInteractiveElement) Enum() *EInteractiveElement {
	p := new(EInteractiveElement)
	*p = x
	return p
}

func (x EInteractiveElement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EInteractiveElement) Descriptor() protoreflect.EnumDescriptor {
	return file_enums_productinfo_proto_enumTypes[1].Descriptor()
}

func (EInteractiveElement) Type() protoreflect.EnumType {
	return &file_enums_productinfo_proto_enumTypes[1]
}

func (x EInteractiveElement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EInteractiveElement) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EInteractiveElement(num)
	return nil
}

// Deprecated: Use EInteractiveElement.Descriptor instead.
func (EInteractiveElement) EnumDescriptor() ([]byte, []int) {
	return file_enums_productinfo_proto_rawDescGZIP(), []int{1}
}

var File_enums_productinfo_proto protoreflect.FileDescriptor

const file_enums_productinfo_proto_rawDesc = "" +
	"\n" +
	"\x17enums_productinfo.proto*\xa2\x02\n" +
	"\x14EContentDescriptorID\x12.\n" +
	"*k_EContentDescriptor_NudityOrSexualContent\x10\x01\x12/\n" +
	"+k_EContentDescriptor_FrequentViolenceOrGore\x10\x02\x12/\n" +
	"+k_EContentDescriptor_AdultOnlySexualContent\x10\x03\x120\n" +
	",k_EContentDescriptor_GratuitousSexualContent\x10\x04\x12)\n" +
	"%k_EContentDescriptor_AnyMatureContent\x10\x05\x12\x1b\n" +
	"\x17k_EContentDescriptorMAX\x10\x06*\xf4\x01\n" +
	"\x13EInteractiveElement\x12!\n" +
	"\x1dk_EInteractiveElement_Invalid\x10\x00\x12)\n" +
	"%k_EInteractiveElement_InGamePurchases\x10\x01\x12:\n" +
	"6k_EInteractiveElement_InGamePurchasesOfRandomizedItems\x10\x02\x12$\n" +
	" k_EInteractiveElement_InGameChat\x10\x03\x12-\n" +
	")k_EInteractiveElement_OnlineInteractivity\x10\x04B\x02H\x01"

var (
	file_enums_productinfo_proto_rawDescOnce sync.Once
	file_enums_productinfo_proto_rawDescData []byte
)

func file_enums_productinfo_proto_rawDescGZIP() []byte {
	file_enums_productinfo_proto_rawDescOnce.Do(func() {
		file_enums_productinfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enums_productinfo_proto_rawDesc), len(file_enums_productinfo_proto_rawDesc)))
	})
	return file_enums_productinfo_proto_rawDescData
}

var file_enums_productinfo_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_enums_productinfo_proto_goTypes = []any{
	(EContentDescriptorID)(0), // 0: EContentDescriptorID
	(EInteractiveElement)(0),  // 1: EInteractiveElement
}
var file_enums_productinfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enums_productinfo_proto_init() }
func file_enums_productinfo_proto_init() {
	if File_enums_productinfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enums_productinfo_proto_rawDesc), len(file_enums_productinfo_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enums_productinfo_proto_goTypes,
		DependencyIndexes: file_enums_productinfo_proto_depIdxs,
		EnumInfos:         file_enums_productinfo_proto_enumTypes,
	}.Build()
	File_enums_productinfo_proto = out.File
	file_enums_productinfo_proto_goTypes = nil
	file_enums_productinfo_proto_depIdxs = nil
}
