// Code generated by protoc-gen-enums. DO NOT EDIT.

package steam

import (
	"net/url"
	"strconv"
)

// EncodeValues implements the query.Encoder interface for EPublishedFileQueryType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EPublishedFileQueryType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EPublishedFileInappropriateProvider.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EPublishedFileInappropriateProvider) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EPublishedFileInappropriateResult.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EPublishedFileInappropriateResult) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EPersonaStateFlag.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EPersonaStateFlag) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EContentCheckProvider.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EContentCheckProvider) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EProfileCustomizationType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EProfileCustomizationType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EPublishedFileStorageSystem.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EPublishedFileStorageSystem) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ECloudStoragePersistState.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ECloudStoragePersistState) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESDCardFormatStage.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESDCardFormatStage) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStorageFormatStage.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStorageFormatStage) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESystemFanControlMode.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESystemFanControlMode) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EColorGamutLabelSet.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EColorGamutLabelSet) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EWindowStackingOrder.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EWindowStackingOrder) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EBluetoothDeviceType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EBluetoothDeviceType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESpeakerConfiguration.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESpeakerConfiguration) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESystemAudioDirection.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESystemAudioDirection) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESystemAudioChannel.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESystemAudioChannel) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESystemAudioPortType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESystemAudioPortType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESystemAudioPortDirection.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESystemAudioPortDirection) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESystemServiceState.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESystemServiceState) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EGraphicsPerfOverlayLevel.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EGraphicsPerfOverlayLevel) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EGPUPerformanceLevel.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EGPUPerformanceLevel) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESplitScalingFilter.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESplitScalingFilter) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESplitScalingScaler.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESplitScalingScaler) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EGamescopeBlurMode.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EGamescopeBlurMode) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESLSHelper.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESLSHelper) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EHDRVisualization.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EHDRVisualization) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EHDRToneMapOperator.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EHDRToneMapOperator) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ECPUGovernor.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ECPUGovernor) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EUpdaterType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EUpdaterType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EUpdaterState.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EUpdaterState) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStorageBlockContentType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStorageBlockContentType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStorageBlockFileSystemType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStorageBlockFileSystemType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStorageDriveMediaType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStorageDriveMediaType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESystemDisplayCompatibilityMode.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESystemDisplayCompatibilityMode) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESteamOSCompatibilityCategory.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESteamOSCompatibilityCategory) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESteamOSCompatibilityResultDisplayType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESteamOSCompatibilityResultDisplayType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESteamDeckCompatibilityCategory.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESteamDeckCompatibilityCategory) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESteamDeckCompatibilityResultDisplayType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESteamDeckCompatibilityResultDisplayType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESteamDeckCompatibilityTestResult.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESteamDeckCompatibilityTestResult) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EACState.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EACState) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EBatteryState.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EBatteryState) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EOSBranch.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EOSBranch) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EBrowserGPUStatus.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EBrowserGPUStatus) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EBrowserFeatureStatus.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EBrowserFeatureStatus) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EGpuDriverId.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EGpuDriverId) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ECommunityItemClass.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ECommunityItemClass) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESteamDeckCompatibilityFeedback.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESteamDeckCompatibilityFeedback) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EProvideDeckFeedbackPreference.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EProvideDeckFeedbackPreference) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EHardwareCompatibilityFeedbackDetails.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EHardwareCompatibilityFeedbackDetails) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EGameFrameRateReportingPreference.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EGameFrameRateReportingPreference) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ETouchGesture.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ETouchGesture) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESessionPersistence.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESessionPersistence) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ENewSteamAnnouncementState.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ENewSteamAnnouncementState) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EForumType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EForumType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ECommentThreadType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ECommentThreadType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EBroadcastPermission.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EBroadcastPermission) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EBroadcastEncoderSetting.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EBroadcastEncoderSetting) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ECloudGamingPlatform.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ECloudGamingPlatform) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ECompromiseDetectionType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ECompromiseDetectionType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EAsyncGameSessionUserState.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EAsyncGameSessionUserState) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EAsyncGameSessionUserVisibility.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EAsyncGameSessionUserVisibility) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EGameRecordingType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EGameRecordingType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EGRMode.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EGRMode) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EExportCodec.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EExportCodec) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EProtoAppType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EProtoAppType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EChildProcessQueryCommand.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EChildProcessQueryCommand) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EChildProcessQueryExitCode.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EChildProcessQueryExitCode) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EWindowsUpdateInstallationImpact.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EWindowsUpdateInstallationImpact) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EWindowsUpdateRebootBehavior.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EWindowsUpdateRebootBehavior) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EExternalSaleEventType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EExternalSaleEventType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EEnhancedMarketAppearanceStatus.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EEnhancedMarketAppearanceStatus) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EContentReportSubjectType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EContentReportSubjectType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EControlledLegalCategoryStatus.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EControlledLegalCategoryStatus) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EContentModeratorLevel.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EContentModeratorLevel) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EContentReportResolution.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EContentReportResolution) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EContentModerationSanction.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EContentModerationSanction) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EContentReportSubjectAction.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EContentReportSubjectAction) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EContentReportReason.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EContentReportReason) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EResolutionAutomation.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EResolutionAutomation) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EPressOutletAction.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EPressOutletAction) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EPressOutletMemberPendingState.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EPressOutletMemberPendingState) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ECommentDeleteReason.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ECommentDeleteReason) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}
