// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: steammessages_steamawards_types.proto

package steam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SteamAward_Localization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *string                `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SteamAward_Localization) Reset() {
	*x = SteamAward_Localization{}
	mi := &file_steammessages_steamawards_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SteamAward_Localization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SteamAward_Localization) ProtoMessage() {}

func (x *SteamAward_Localization) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_steamawards_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SteamAward_Localization.ProtoReflect.Descriptor instead.
func (*SteamAward_Localization) Descriptor() ([]byte, []int) {
	return file_steammessages_steamawards_types_proto_rawDescGZIP(), []int{0}
}

func (x *SteamAward_Localization) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

type SteamAward struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Voteid        *int32                   `protobuf:"varint,1,opt,name=voteid" json:"voteid,omitempty"`
	Localization  *SteamAward_Localization `protobuf:"bytes,2,opt,name=localization" json:"localization,omitempty"`
	AwardYear     *int32                   `protobuf:"varint,3,opt,name=award_year,json=awardYear" json:"award_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SteamAward) Reset() {
	*x = SteamAward{}
	mi := &file_steammessages_steamawards_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SteamAward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SteamAward) ProtoMessage() {}

func (x *SteamAward) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_steamawards_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SteamAward.ProtoReflect.Descriptor instead.
func (*SteamAward) Descriptor() ([]byte, []int) {
	return file_steammessages_steamawards_types_proto_rawDescGZIP(), []int{1}
}

func (x *SteamAward) GetVoteid() int32 {
	if x != nil && x.Voteid != nil {
		return *x.Voteid
	}
	return 0
}

func (x *SteamAward) GetLocalization() *SteamAward_Localization {
	if x != nil {
		return x.Localization
	}
	return nil
}

func (x *SteamAward) GetAwardYear() int32 {
	if x != nil && x.AwardYear != nil {
		return *x.AwardYear
	}
	return 0
}

var File_steammessages_steamawards_types_proto protoreflect.FileDescriptor

const file_steammessages_steamawards_types_proto_rawDesc = "" +
	"\n" +
	"%steammessages_steamawards_types.proto\"/\n" +
	"\x17SteamAward_Localization\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"\x81\x01\n" +
	"\n" +
	"SteamAward\x12\x16\n" +
	"\x06voteid\x18\x01 \x01(\x05R\x06voteid\x12<\n" +
	"\flocalization\x18\x02 \x01(\v2\x18.SteamAward_LocalizationR\flocalization\x12\x1d\n" +
	"\n" +
	"award_year\x18\x03 \x01(\x05R\tawardYearB\x02H\x01"

var (
	file_steammessages_steamawards_types_proto_rawDescOnce sync.Once
	file_steammessages_steamawards_types_proto_rawDescData []byte
)

func file_steammessages_steamawards_types_proto_rawDescGZIP() []byte {
	file_steammessages_steamawards_types_proto_rawDescOnce.Do(func() {
		file_steammessages_steamawards_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steammessages_steamawards_types_proto_rawDesc), len(file_steammessages_steamawards_types_proto_rawDesc)))
	})
	return file_steammessages_steamawards_types_proto_rawDescData
}

var file_steammessages_steamawards_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_steammessages_steamawards_types_proto_goTypes = []any{
	(*SteamAward_Localization)(nil), // 0: SteamAward_Localization
	(*SteamAward)(nil),              // 1: SteamAward
}
var file_steammessages_steamawards_types_proto_depIdxs = []int32{
	0, // 0: SteamAward.localization:type_name -> SteamAward_Localization
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_steammessages_steamawards_types_proto_init() }
func file_steammessages_steamawards_types_proto_init() {
	if File_steammessages_steamawards_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_steamawards_types_proto_rawDesc), len(file_steammessages_steamawards_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_steammessages_steamawards_types_proto_goTypes,
		DependencyIndexes: file_steammessages_steamawards_types_proto_depIdxs,
		MessageInfos:      file_steammessages_steamawards_types_proto_msgTypes,
	}.Build()
	File_steammessages_steamawards_types_proto = out.File
	file_steammessages_steamawards_types_proto_goTypes = nil
	file_steammessages_steamawards_types_proto_depIdxs = nil
}
