// Code generated by protoc-gen-enums. DO NOT EDIT.

package steam

import (
	"net/url"
	"strconv"
)

// EncodeValues implements the query.Encoder interface for EAchievementProgressType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EAchievementProgressType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EProfileCustomizationStyle.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EProfileCustomizationStyle) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EAgreementType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EAgreementType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ENotificationSetting.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ENotificationSetting) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ETextFilterSetting.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ETextFilterSetting) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}
