// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: steammessages_childprocessquery.proto

package steam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EChildProcessQueryCommand int32

const (
	EChildProcessQueryCommand_k_EChildProcessQueryCommand_Invalid                EChildProcessQueryCommand = 0
	EChildProcessQueryCommand_k_EChildProcessQueryCommand_GpuTopology            EChildProcessQueryCommand = 1
	EChildProcessQueryCommand_k_EChildProcessQueryCommand_EnumerateHostAppsLinux EChildProcessQueryCommand = 2
	EChildProcessQueryCommand_k_EChildProcessQueryCommand_GetHostAppLinux        EChildProcessQueryCommand = 3
	EChildProcessQueryCommand_k_EChildProcessQueryCommand_Max                    EChildProcessQueryCommand = 4
)

// Enum value maps for EChildProcessQueryCommand.
var (
	EChildProcessQueryCommand_name = map[int32]string{
		0: "k_EChildProcessQueryCommand_Invalid",
		1: "k_EChildProcessQueryCommand_GpuTopology",
		2: "k_EChildProcessQueryCommand_EnumerateHostAppsLinux",
		3: "k_EChildProcessQueryCommand_GetHostAppLinux",
		4: "k_EChildProcessQueryCommand_Max",
	}
	EChildProcessQueryCommand_value = map[string]int32{
		"k_EChildProcessQueryCommand_Invalid":                0,
		"k_EChildProcessQueryCommand_GpuTopology":            1,
		"k_EChildProcessQueryCommand_EnumerateHostAppsLinux": 2,
		"k_EChildProcessQueryCommand_GetHostAppLinux":        3,
		"k_EChildProcessQueryCommand_Max":                    4,
	}
)

func (x EChildProcessQueryCommand) Enum() *EChildProcessQueryCommand {
	p := new(EChildProcessQueryCommand)
	*p = x
	return p
}

func (x EChildProcessQueryCommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EChildProcessQueryCommand) Descriptor() protoreflect.EnumDescriptor {
	return file_steammessages_childprocessquery_proto_enumTypes[0].Descriptor()
}

func (EChildProcessQueryCommand) Type() protoreflect.EnumType {
	return &file_steammessages_childprocessquery_proto_enumTypes[0]
}

func (x EChildProcessQueryCommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EChildProcessQueryCommand) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EChildProcessQueryCommand(num)
	return nil
}

// Deprecated: Use EChildProcessQueryCommand.Descriptor instead.
func (EChildProcessQueryCommand) EnumDescriptor() ([]byte, []int) {
	return file_steammessages_childprocessquery_proto_rawDescGZIP(), []int{0}
}

type CMsgChildProcessQueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*CMsgChildProcessQueryResponse_GpuTopology
	//	*CMsgChildProcessQueryResponse_HostApps
	//	*CMsgChildProcessQueryResponse_HostApp
	Response      isCMsgChildProcessQueryResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgChildProcessQueryResponse) Reset() {
	*x = CMsgChildProcessQueryResponse{}
	mi := &file_steammessages_childprocessquery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgChildProcessQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgChildProcessQueryResponse) ProtoMessage() {}

func (x *CMsgChildProcessQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_childprocessquery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgChildProcessQueryResponse.ProtoReflect.Descriptor instead.
func (*CMsgChildProcessQueryResponse) Descriptor() ([]byte, []int) {
	return file_steammessages_childprocessquery_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgChildProcessQueryResponse) GetResponse() isCMsgChildProcessQueryResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CMsgChildProcessQueryResponse) GetGpuTopology() *CMsgChildProcessQueryGpuTopology {
	if x != nil {
		if x, ok := x.Response.(*CMsgChildProcessQueryResponse_GpuTopology); ok {
			return x.GpuTopology
		}
	}
	return nil
}

func (x *CMsgChildProcessQueryResponse) GetHostApps() *CMsgChildProcessQueryEnumerateHostAppsLinux {
	if x != nil {
		if x, ok := x.Response.(*CMsgChildProcessQueryResponse_HostApps); ok {
			return x.HostApps
		}
	}
	return nil
}

func (x *CMsgChildProcessQueryResponse) GetHostApp() *CMsgChildProcessQueryGetHostAppLinux {
	if x != nil {
		if x, ok := x.Response.(*CMsgChildProcessQueryResponse_HostApp); ok {
			return x.HostApp
		}
	}
	return nil
}

type isCMsgChildProcessQueryResponse_Response interface {
	isCMsgChildProcessQueryResponse_Response()
}

type CMsgChildProcessQueryResponse_GpuTopology struct {
	GpuTopology *CMsgChildProcessQueryGpuTopology `protobuf:"bytes,1,opt,name=gpu_topology,json=gpuTopology,oneof"`
}

type CMsgChildProcessQueryResponse_HostApps struct {
	HostApps *CMsgChildProcessQueryEnumerateHostAppsLinux `protobuf:"bytes,2,opt,name=host_apps,json=hostApps,oneof"`
}

type CMsgChildProcessQueryResponse_HostApp struct {
	HostApp *CMsgChildProcessQueryGetHostAppLinux `protobuf:"bytes,3,opt,name=host_app,json=hostApp,oneof"`
}

func (*CMsgChildProcessQueryResponse_GpuTopology) isCMsgChildProcessQueryResponse_Response() {}

func (*CMsgChildProcessQueryResponse_HostApps) isCMsgChildProcessQueryResponse_Response() {}

func (*CMsgChildProcessQueryResponse_HostApp) isCMsgChildProcessQueryResponse_Response() {}

type CMsgChildProcessQueryGpuTopology struct {
	state         protoimpl.MessageState                      `protogen:"open.v1"`
	Gpus          []*CMsgChildProcessQueryGpuTopology_GpuInfo `protobuf:"bytes,1,rep,name=gpus" json:"gpus,omitempty"`
	DefaultGpuId  *uint32                                     `protobuf:"varint,2,opt,name=default_gpu_id,json=defaultGpuId" json:"default_gpu_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgChildProcessQueryGpuTopology) Reset() {
	*x = CMsgChildProcessQueryGpuTopology{}
	mi := &file_steammessages_childprocessquery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgChildProcessQueryGpuTopology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgChildProcessQueryGpuTopology) ProtoMessage() {}

func (x *CMsgChildProcessQueryGpuTopology) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_childprocessquery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgChildProcessQueryGpuTopology.ProtoReflect.Descriptor instead.
func (*CMsgChildProcessQueryGpuTopology) Descriptor() ([]byte, []int) {
	return file_steammessages_childprocessquery_proto_rawDescGZIP(), []int{1}
}

func (x *CMsgChildProcessQueryGpuTopology) GetGpus() []*CMsgChildProcessQueryGpuTopology_GpuInfo {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *CMsgChildProcessQueryGpuTopology) GetDefaultGpuId() uint32 {
	if x != nil && x.DefaultGpuId != nil {
		return *x.DefaultGpuId
	}
	return 0
}

type CMsgHostAppInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	PathExe       *string                `protobuf:"bytes,2,opt,name=path_exe,json=pathExe" json:"path_exe,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
	PathShortcut  *string                `protobuf:"bytes,4,opt,name=path_shortcut,json=pathShortcut" json:"path_shortcut,omitempty"`
	IconName      *string                `protobuf:"bytes,5,opt,name=icon_name,json=iconName" json:"icon_name,omitempty"`
	IsTerminal    *bool                  `protobuf:"varint,6,opt,name=is_terminal,json=isTerminal" json:"is_terminal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgHostAppInfo) Reset() {
	*x = CMsgHostAppInfo{}
	mi := &file_steammessages_childprocessquery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgHostAppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgHostAppInfo) ProtoMessage() {}

func (x *CMsgHostAppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_childprocessquery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgHostAppInfo.ProtoReflect.Descriptor instead.
func (*CMsgHostAppInfo) Descriptor() ([]byte, []int) {
	return file_steammessages_childprocessquery_proto_rawDescGZIP(), []int{2}
}

func (x *CMsgHostAppInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CMsgHostAppInfo) GetPathExe() string {
	if x != nil && x.PathExe != nil {
		return *x.PathExe
	}
	return ""
}

func (x *CMsgHostAppInfo) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CMsgHostAppInfo) GetPathShortcut() string {
	if x != nil && x.PathShortcut != nil {
		return *x.PathShortcut
	}
	return ""
}

func (x *CMsgHostAppInfo) GetIconName() string {
	if x != nil && x.IconName != nil {
		return *x.IconName
	}
	return ""
}

func (x *CMsgHostAppInfo) GetIsTerminal() bool {
	if x != nil && x.IsTerminal != nil {
		return *x.IsTerminal
	}
	return false
}

type CMsgChildProcessQueryEnumerateHostAppsLinux struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []*CMsgHostAppInfo     `protobuf:"bytes,1,rep,name=apps" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgChildProcessQueryEnumerateHostAppsLinux) Reset() {
	*x = CMsgChildProcessQueryEnumerateHostAppsLinux{}
	mi := &file_steammessages_childprocessquery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgChildProcessQueryEnumerateHostAppsLinux) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgChildProcessQueryEnumerateHostAppsLinux) ProtoMessage() {}

func (x *CMsgChildProcessQueryEnumerateHostAppsLinux) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_childprocessquery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgChildProcessQueryEnumerateHostAppsLinux.ProtoReflect.Descriptor instead.
func (*CMsgChildProcessQueryEnumerateHostAppsLinux) Descriptor() ([]byte, []int) {
	return file_steammessages_childprocessquery_proto_rawDescGZIP(), []int{3}
}

func (x *CMsgChildProcessQueryEnumerateHostAppsLinux) GetApps() []*CMsgHostAppInfo {
	if x != nil {
		return x.Apps
	}
	return nil
}

type CMsgChildProcessQueryGetHostAppLinux struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *CMsgHostAppInfo       `protobuf:"bytes,1,opt,name=app" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgChildProcessQueryGetHostAppLinux) Reset() {
	*x = CMsgChildProcessQueryGetHostAppLinux{}
	mi := &file_steammessages_childprocessquery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgChildProcessQueryGetHostAppLinux) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgChildProcessQueryGetHostAppLinux) ProtoMessage() {}

func (x *CMsgChildProcessQueryGetHostAppLinux) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_childprocessquery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgChildProcessQueryGetHostAppLinux.ProtoReflect.Descriptor instead.
func (*CMsgChildProcessQueryGetHostAppLinux) Descriptor() ([]byte, []int) {
	return file_steammessages_childprocessquery_proto_rawDescGZIP(), []int{4}
}

func (x *CMsgChildProcessQueryGetHostAppLinux) GetApp() *CMsgHostAppInfo {
	if x != nil {
		return x.App
	}
	return nil
}

type CMsgChildProcessQueryGpuTopology_GpuInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name               *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	VramSizeBytes      *uint64                `protobuf:"varint,3,opt,name=vram_size_bytes,json=vramSizeBytes" json:"vram_size_bytes,omitempty"`
	DriverId           *EGpuDriverId          `protobuf:"varint,4,opt,name=driver_id,json=driverId,enum=EGpuDriverId,def=0" json:"driver_id,omitempty"`
	DriverVersionMajor *int32                 `protobuf:"varint,5,opt,name=driver_version_major,json=driverVersionMajor" json:"driver_version_major,omitempty"`
	DriverVersionMinor *int32                 `protobuf:"varint,6,opt,name=driver_version_minor,json=driverVersionMinor" json:"driver_version_minor,omitempty"`
	DriverVersionPatch *int32                 `protobuf:"varint,7,opt,name=driver_version_patch,json=driverVersionPatch" json:"driver_version_patch,omitempty"`
	Luid               *uint64                `protobuf:"varint,8,opt,name=luid" json:"luid,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

// Default values for CMsgChildProcessQueryGpuTopology_GpuInfo fields.
const (
	Default_CMsgChildProcessQueryGpuTopology_GpuInfo_DriverId = EGpuDriverId_k_EGpuDriverId_Invalid
)

func (x *CMsgChildProcessQueryGpuTopology_GpuInfo) Reset() {
	*x = CMsgChildProcessQueryGpuTopology_GpuInfo{}
	mi := &file_steammessages_childprocessquery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgChildProcessQueryGpuTopology_GpuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgChildProcessQueryGpuTopology_GpuInfo) ProtoMessage() {}

func (x *CMsgChildProcessQueryGpuTopology_GpuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_childprocessquery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgChildProcessQueryGpuTopology_GpuInfo.ProtoReflect.Descriptor instead.
func (*CMsgChildProcessQueryGpuTopology_GpuInfo) Descriptor() ([]byte, []int) {
	return file_steammessages_childprocessquery_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CMsgChildProcessQueryGpuTopology_GpuInfo) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *CMsgChildProcessQueryGpuTopology_GpuInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CMsgChildProcessQueryGpuTopology_GpuInfo) GetVramSizeBytes() uint64 {
	if x != nil && x.VramSizeBytes != nil {
		return *x.VramSizeBytes
	}
	return 0
}

func (x *CMsgChildProcessQueryGpuTopology_GpuInfo) GetDriverId() EGpuDriverId {
	if x != nil && x.DriverId != nil {
		return *x.DriverId
	}
	return Default_CMsgChildProcessQueryGpuTopology_GpuInfo_DriverId
}

func (x *CMsgChildProcessQueryGpuTopology_GpuInfo) GetDriverVersionMajor() int32 {
	if x != nil && x.DriverVersionMajor != nil {
		return *x.DriverVersionMajor
	}
	return 0
}

func (x *CMsgChildProcessQueryGpuTopology_GpuInfo) GetDriverVersionMinor() int32 {
	if x != nil && x.DriverVersionMinor != nil {
		return *x.DriverVersionMinor
	}
	return 0
}

func (x *CMsgChildProcessQueryGpuTopology_GpuInfo) GetDriverVersionPatch() int32 {
	if x != nil && x.DriverVersionPatch != nil {
		return *x.DriverVersionPatch
	}
	return 0
}

func (x *CMsgChildProcessQueryGpuTopology_GpuInfo) GetLuid() uint64 {
	if x != nil && x.Luid != nil {
		return *x.Luid
	}
	return 0
}

var File_steammessages_childprocessquery_proto protoreflect.FileDescriptor

const file_steammessages_childprocessquery_proto_rawDesc = "" +
	"\n" +
	"%steammessages_childprocessquery.proto\x1a\venums.proto\"\x84\x02\n" +
	"\x1dCMsgChildProcessQueryResponse\x12F\n" +
	"\fgpu_topology\x18\x01 \x01(\v2!.CMsgChildProcessQueryGpuTopologyH\x00R\vgpuTopology\x12K\n" +
	"\thost_apps\x18\x02 \x01(\v2,.CMsgChildProcessQueryEnumerateHostAppsLinuxH\x00R\bhostApps\x12B\n" +
	"\bhost_app\x18\x03 \x01(\v2%.CMsgChildProcessQueryGetHostAppLinuxH\x00R\ahostAppB\n" +
	"\n" +
	"\bresponse\"\xcd\x03\n" +
	" CMsgChildProcessQueryGpuTopology\x12=\n" +
	"\x04gpus\x18\x01 \x03(\v2).CMsgChildProcessQueryGpuTopology.GpuInfoR\x04gpus\x12$\n" +
	"\x0edefault_gpu_id\x18\x02 \x01(\rR\fdefaultGpuId\x1a\xc3\x02\n" +
	"\aGpuInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0fvram_size_bytes\x18\x03 \x01(\x04R\rvramSizeBytes\x12B\n" +
	"\tdriver_id\x18\x04 \x01(\x0e2\r.EGpuDriverId:\x16k_EGpuDriverId_InvalidR\bdriverId\x120\n" +
	"\x14driver_version_major\x18\x05 \x01(\x05R\x12driverVersionMajor\x120\n" +
	"\x14driver_version_minor\x18\x06 \x01(\x05R\x12driverVersionMinor\x120\n" +
	"\x14driver_version_patch\x18\a \x01(\x05R\x12driverVersionPatch\x12\x12\n" +
	"\x04luid\x18\b \x01(\x04R\x04luid\"\xb7\x01\n" +
	"\x0fCMsgHostAppInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bpath_exe\x18\x02 \x01(\tR\apathExe\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12#\n" +
	"\rpath_shortcut\x18\x04 \x01(\tR\fpathShortcut\x12\x1b\n" +
	"\ticon_name\x18\x05 \x01(\tR\biconName\x12\x1f\n" +
	"\vis_terminal\x18\x06 \x01(\bR\n" +
	"isTerminal\"S\n" +
	"+CMsgChildProcessQueryEnumerateHostAppsLinux\x12$\n" +
	"\x04apps\x18\x01 \x03(\v2\x10.CMsgHostAppInfoR\x04apps\"J\n" +
	"$CMsgChildProcessQueryGetHostAppLinux\x12\"\n" +
	"\x03app\x18\x01 \x01(\v2\x10.CMsgHostAppInfoR\x03app*\xff\x01\n" +
	"\x19EChildProcessQueryCommand\x12'\n" +
	"#k_EChildProcessQueryCommand_Invalid\x10\x00\x12+\n" +
	"'k_EChildProcessQueryCommand_GpuTopology\x10\x01\x126\n" +
	"2k_EChildProcessQueryCommand_EnumerateHostAppsLinux\x10\x02\x12/\n" +
	"+k_EChildProcessQueryCommand_GetHostAppLinux\x10\x03\x12#\n" +
	"\x1fk_EChildProcessQueryCommand_Max\x10\x04B\x05H\x01\x80\x01\x00"

var (
	file_steammessages_childprocessquery_proto_rawDescOnce sync.Once
	file_steammessages_childprocessquery_proto_rawDescData []byte
)

func file_steammessages_childprocessquery_proto_rawDescGZIP() []byte {
	file_steammessages_childprocessquery_proto_rawDescOnce.Do(func() {
		file_steammessages_childprocessquery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steammessages_childprocessquery_proto_rawDesc), len(file_steammessages_childprocessquery_proto_rawDesc)))
	})
	return file_steammessages_childprocessquery_proto_rawDescData
}

var file_steammessages_childprocessquery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_steammessages_childprocessquery_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_steammessages_childprocessquery_proto_goTypes = []any{
	(EChildProcessQueryCommand)(0),                      // 0: EChildProcessQueryCommand
	(*CMsgChildProcessQueryResponse)(nil),               // 1: CMsgChildProcessQueryResponse
	(*CMsgChildProcessQueryGpuTopology)(nil),            // 2: CMsgChildProcessQueryGpuTopology
	(*CMsgHostAppInfo)(nil),                             // 3: CMsgHostAppInfo
	(*CMsgChildProcessQueryEnumerateHostAppsLinux)(nil), // 4: CMsgChildProcessQueryEnumerateHostAppsLinux
	(*CMsgChildProcessQueryGetHostAppLinux)(nil),        // 5: CMsgChildProcessQueryGetHostAppLinux
	(*CMsgChildProcessQueryGpuTopology_GpuInfo)(nil),    // 6: CMsgChildProcessQueryGpuTopology.GpuInfo
	(EGpuDriverId)(0),                                   // 7: EGpuDriverId
}
var file_steammessages_childprocessquery_proto_depIdxs = []int32{
	2, // 0: CMsgChildProcessQueryResponse.gpu_topology:type_name -> CMsgChildProcessQueryGpuTopology
	4, // 1: CMsgChildProcessQueryResponse.host_apps:type_name -> CMsgChildProcessQueryEnumerateHostAppsLinux
	5, // 2: CMsgChildProcessQueryResponse.host_app:type_name -> CMsgChildProcessQueryGetHostAppLinux
	6, // 3: CMsgChildProcessQueryGpuTopology.gpus:type_name -> CMsgChildProcessQueryGpuTopology.GpuInfo
	3, // 4: CMsgChildProcessQueryEnumerateHostAppsLinux.apps:type_name -> CMsgHostAppInfo
	3, // 5: CMsgChildProcessQueryGetHostAppLinux.app:type_name -> CMsgHostAppInfo
	7, // 6: CMsgChildProcessQueryGpuTopology.GpuInfo.driver_id:type_name -> EGpuDriverId
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_steammessages_childprocessquery_proto_init() }
func file_steammessages_childprocessquery_proto_init() {
	if File_steammessages_childprocessquery_proto != nil {
		return
	}
	file_enums_proto_init()
	file_steammessages_childprocessquery_proto_msgTypes[0].OneofWrappers = []any{
		(*CMsgChildProcessQueryResponse_GpuTopology)(nil),
		(*CMsgChildProcessQueryResponse_HostApps)(nil),
		(*CMsgChildProcessQueryResponse_HostApp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_childprocessquery_proto_rawDesc), len(file_steammessages_childprocessquery_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_steammessages_childprocessquery_proto_goTypes,
		DependencyIndexes: file_steammessages_childprocessquery_proto_depIdxs,
		EnumInfos:         file_steammessages_childprocessquery_proto_enumTypes,
		MessageInfos:      file_steammessages_childprocessquery_proto_msgTypes,
	}.Build()
	File_steammessages_childprocessquery_proto = out.File
	file_steammessages_childprocessquery_proto_goTypes = nil
	file_steammessages_childprocessquery_proto_depIdxs = nil
}
