// Code generated by protoc-gen-enums. DO NOT EDIT.

package steam

import (
	"net/url"
	"strconv"
)

// EncodeValues implements the query.Encoder interface for EClanImageGroup.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EClanImageGroup) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EClanImageFileType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EClanImageFileType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EPartnerEventDisplayLocation.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EPartnerEventDisplayLocation) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ECommentReportAction.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ECommentReportAction) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}
