// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: steammessages_appratings_types.proto

package steam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ERatingAgency int32

const (
	ERatingAgency_k_ERatingAgency_Invalid         ERatingAgency = 0
	ERatingAgency_k_ERatingAgency_ESRB            ERatingAgency = 1
	ERatingAgency_k_ERatingAgency_PEGI            ERatingAgency = 2
	ERatingAgency_k_ERatingAgency_BBFC            ERatingAgency = 3
	ERatingAgency_k_ERatingAgency_USK             ERatingAgency = 4
	ERatingAgency_k_ERatingAgency_OFLC_AU         ERatingAgency = 5
	ERatingAgency_k_ERatingAgency_OFLC_NZ         ERatingAgency = 6
	ERatingAgency_k_ERatingAgency_CERO            ERatingAgency = 7
	ERatingAgency_k_ERatingAgency_GRAC            ERatingAgency = 8
	ERatingAgency_k_ERatingAgency_GMEDIA          ERatingAgency = 9
	ERatingAgency_k_ERatingAgency_DEJUS           ERatingAgency = 10
	ERatingAgency_k_ERatingAgency_IMDA            ERatingAgency = 11
	ERatingAgency_k_ERatingAgency_FPB             ERatingAgency = 12
	ERatingAgency_k_ERatingAgency_TESRI           ERatingAgency = 13
	ERatingAgency_k_ERatingAgency_RARS            ERatingAgency = 14
	ERatingAgency_k_ERatingAgency_AGCOM           ERatingAgency = 15
	ERatingAgency_k_ERatingAgency_IGRS            ERatingAgency = 16
	ERatingAgency_k_ERatingAgency_Steam_Germany   ERatingAgency = 17
	ERatingAgency_k_ERatingAgency_Steam_Australia ERatingAgency = 18
	ERatingAgency_k_ERatingAgency_CADPA           ERatingAgency = 19
)

// Enum value maps for ERatingAgency.
var (
	ERatingAgency_name = map[int32]string{
		0:  "k_ERatingAgency_Invalid",
		1:  "k_ERatingAgency_ESRB",
		2:  "k_ERatingAgency_PEGI",
		3:  "k_ERatingAgency_BBFC",
		4:  "k_ERatingAgency_USK",
		5:  "k_ERatingAgency_OFLC_AU",
		6:  "k_ERatingAgency_OFLC_NZ",
		7:  "k_ERatingAgency_CERO",
		8:  "k_ERatingAgency_GRAC",
		9:  "k_ERatingAgency_GMEDIA",
		10: "k_ERatingAgency_DEJUS",
		11: "k_ERatingAgency_IMDA",
		12: "k_ERatingAgency_FPB",
		13: "k_ERatingAgency_TESRI",
		14: "k_ERatingAgency_RARS",
		15: "k_ERatingAgency_AGCOM",
		16: "k_ERatingAgency_IGRS",
		17: "k_ERatingAgency_Steam_Germany",
		18: "k_ERatingAgency_Steam_Australia",
		19: "k_ERatingAgency_CADPA",
	}
	ERatingAgency_value = map[string]int32{
		"k_ERatingAgency_Invalid":         0,
		"k_ERatingAgency_ESRB":            1,
		"k_ERatingAgency_PEGI":            2,
		"k_ERatingAgency_BBFC":            3,
		"k_ERatingAgency_USK":             4,
		"k_ERatingAgency_OFLC_AU":         5,
		"k_ERatingAgency_OFLC_NZ":         6,
		"k_ERatingAgency_CERO":            7,
		"k_ERatingAgency_GRAC":            8,
		"k_ERatingAgency_GMEDIA":          9,
		"k_ERatingAgency_DEJUS":           10,
		"k_ERatingAgency_IMDA":            11,
		"k_ERatingAgency_FPB":             12,
		"k_ERatingAgency_TESRI":           13,
		"k_ERatingAgency_RARS":            14,
		"k_ERatingAgency_AGCOM":           15,
		"k_ERatingAgency_IGRS":            16,
		"k_ERatingAgency_Steam_Germany":   17,
		"k_ERatingAgency_Steam_Australia": 18,
		"k_ERatingAgency_CADPA":           19,
	}
)

func (x ERatingAgency) Enum() *ERatingAgency {
	p := new(ERatingAgency)
	*p = x
	return p
}

func (x ERatingAgency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ERatingAgency) Descriptor() protoreflect.EnumDescriptor {
	return file_steammessages_appratings_types_proto_enumTypes[0].Descriptor()
}

func (ERatingAgency) Type() protoreflect.EnumType {
	return &file_steammessages_appratings_types_proto_enumTypes[0]
}

func (x ERatingAgency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ERatingAgency) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ERatingAgency(num)
	return nil
}

// Deprecated: Use ERatingAgency.Descriptor instead.
func (ERatingAgency) EnumDescriptor() ([]byte, []int) {
	return file_steammessages_appratings_types_proto_rawDescGZIP(), []int{0}
}

type EAppRatingSource int32

const (
	EAppRatingSource_k_EAppRatingSource_Invalid   EAppRatingSource = 0
	EAppRatingSource_k_EAppRatingSource_Official  EAppRatingSource = 1
	EAppRatingSource_k_EAppRatingSource_Generated EAppRatingSource = 2
)

// Enum value maps for EAppRatingSource.
var (
	EAppRatingSource_name = map[int32]string{
		0: "k_EAppRatingSource_Invalid",
		1: "k_EAppRatingSource_Official",
		2: "k_EAppRatingSource_Generated",
	}
	EAppRatingSource_value = map[string]int32{
		"k_EAppRatingSource_Invalid":   0,
		"k_EAppRatingSource_Official":  1,
		"k_EAppRatingSource_Generated": 2,
	}
)

func (x EAppRatingSource) Enum() *EAppRatingSource {
	p := new(EAppRatingSource)
	*p = x
	return p
}

func (x EAppRatingSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EAppRatingSource) Descriptor() protoreflect.EnumDescriptor {
	return file_steammessages_appratings_types_proto_enumTypes[1].Descriptor()
}

func (EAppRatingSource) Type() protoreflect.EnumType {
	return &file_steammessages_appratings_types_proto_enumTypes[1]
}

func (x EAppRatingSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EAppRatingSource) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EAppRatingSource(num)
	return nil
}

// Deprecated: Use EAppRatingSource.Descriptor instead.
func (EAppRatingSource) EnumDescriptor() ([]byte, []int) {
	return file_steammessages_appratings_types_proto_rawDescGZIP(), []int{1}
}

type AppRatingAuxData struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Descriptors                    []string               `protobuf:"bytes,1,rep,name=descriptors" json:"descriptors,omitempty"`
	InteractiveElements            []string               `protobuf:"bytes,2,rep,name=interactive_elements,json=interactiveElements" json:"interactive_elements,omitempty"`
	OfficialId                     *string                `protobuf:"bytes,3,opt,name=official_id,json=officialId" json:"official_id,omitempty"`
	EsrbOnlineMusicNotRated        *bool                  `protobuf:"varint,4,opt,name=esrb_online_music_not_rated,json=esrbOnlineMusicNotRated" json:"esrb_online_music_not_rated,omitempty"`
	EsrbOnlineInteractionsNotRated *bool                  `protobuf:"varint,5,opt,name=esrb_online_interactions_not_rated,json=esrbOnlineInteractionsNotRated" json:"esrb_online_interactions_not_rated,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *AppRatingAuxData) Reset() {
	*x = AppRatingAuxData{}
	mi := &file_steammessages_appratings_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppRatingAuxData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppRatingAuxData) ProtoMessage() {}

func (x *AppRatingAuxData) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_appratings_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppRatingAuxData.ProtoReflect.Descriptor instead.
func (*AppRatingAuxData) Descriptor() ([]byte, []int) {
	return file_steammessages_appratings_types_proto_rawDescGZIP(), []int{0}
}

func (x *AppRatingAuxData) GetDescriptors() []string {
	if x != nil {
		return x.Descriptors
	}
	return nil
}

func (x *AppRatingAuxData) GetInteractiveElements() []string {
	if x != nil {
		return x.InteractiveElements
	}
	return nil
}

func (x *AppRatingAuxData) GetOfficialId() string {
	if x != nil && x.OfficialId != nil {
		return *x.OfficialId
	}
	return ""
}

func (x *AppRatingAuxData) GetEsrbOnlineMusicNotRated() bool {
	if x != nil && x.EsrbOnlineMusicNotRated != nil {
		return *x.EsrbOnlineMusicNotRated
	}
	return false
}

func (x *AppRatingAuxData) GetEsrbOnlineInteractionsNotRated() bool {
	if x != nil && x.EsrbOnlineInteractionsNotRated != nil {
		return *x.EsrbOnlineInteractionsNotRated
	}
	return false
}

type AppRating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RatingAgency  *ERatingAgency         `protobuf:"varint,1,opt,name=rating_agency,json=ratingAgency,enum=ERatingAgency,def=0" json:"rating_agency,omitempty"`
	Rating        *string                `protobuf:"bytes,2,opt,name=rating" json:"rating,omitempty"`
	Source        *EAppRatingSource      `protobuf:"varint,3,opt,name=source,enum=EAppRatingSource,def=0" json:"source,omitempty"`
	Banned        *bool                  `protobuf:"varint,4,opt,name=banned" json:"banned,omitempty"`
	RequiredAge   *uint32                `protobuf:"varint,5,opt,name=required_age,json=requiredAge" json:"required_age,omitempty"`
	UseAgeGate    *bool                  `protobuf:"varint,6,opt,name=use_age_gate,json=useAgeGate" json:"use_age_gate,omitempty"`
	AuxData       *AppRatingAuxData      `protobuf:"bytes,7,opt,name=aux_data,json=auxData" json:"aux_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for AppRating fields.
const (
	Default_AppRating_RatingAgency = ERatingAgency_k_ERatingAgency_Invalid
	Default_AppRating_Source       = EAppRatingSource_k_EAppRatingSource_Invalid
)

func (x *AppRating) Reset() {
	*x = AppRating{}
	mi := &file_steammessages_appratings_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppRating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppRating) ProtoMessage() {}

func (x *AppRating) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_appratings_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppRating.ProtoReflect.Descriptor instead.
func (*AppRating) Descriptor() ([]byte, []int) {
	return file_steammessages_appratings_types_proto_rawDescGZIP(), []int{1}
}

func (x *AppRating) GetRatingAgency() ERatingAgency {
	if x != nil && x.RatingAgency != nil {
		return *x.RatingAgency
	}
	return Default_AppRating_RatingAgency
}

func (x *AppRating) GetRating() string {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return ""
}

func (x *AppRating) GetSource() EAppRatingSource {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return Default_AppRating_Source
}

func (x *AppRating) GetBanned() bool {
	if x != nil && x.Banned != nil {
		return *x.Banned
	}
	return false
}

func (x *AppRating) GetRequiredAge() uint32 {
	if x != nil && x.RequiredAge != nil {
		return *x.RequiredAge
	}
	return 0
}

func (x *AppRating) GetUseAgeGate() bool {
	if x != nil && x.UseAgeGate != nil {
		return *x.UseAgeGate
	}
	return false
}

func (x *AppRating) GetAuxData() *AppRatingAuxData {
	if x != nil {
		return x.AuxData
	}
	return nil
}

var File_steammessages_appratings_types_proto protoreflect.FileDescriptor

const file_steammessages_appratings_types_proto_rawDesc = "" +
	"\n" +
	"$steammessages_appratings_types.proto\"\x92\x02\n" +
	"\x10AppRatingAuxData\x12 \n" +
	"\vdescriptors\x18\x01 \x03(\tR\vdescriptors\x121\n" +
	"\x14interactive_elements\x18\x02 \x03(\tR\x13interactiveElements\x12\x1f\n" +
	"\vofficial_id\x18\x03 \x01(\tR\n" +
	"officialId\x12<\n" +
	"\x1besrb_online_music_not_rated\x18\x04 \x01(\bR\x17esrbOnlineMusicNotRated\x12J\n" +
	"\"esrb_online_interactions_not_rated\x18\x05 \x01(\bR\x1eesrbOnlineInteractionsNotRated\"\xc3\x02\n" +
	"\tAppRating\x12L\n" +
	"\rrating_agency\x18\x01 \x01(\x0e2\x0e.ERatingAgency:\x17k_ERatingAgency_InvalidR\fratingAgency\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\tR\x06rating\x12E\n" +
	"\x06source\x18\x03 \x01(\x0e2\x11.EAppRatingSource:\x1ak_EAppRatingSource_InvalidR\x06source\x12\x16\n" +
	"\x06banned\x18\x04 \x01(\bR\x06banned\x12!\n" +
	"\frequired_age\x18\x05 \x01(\rR\vrequiredAge\x12 \n" +
	"\fuse_age_gate\x18\x06 \x01(\bR\n" +
	"useAgeGate\x12,\n" +
	"\baux_data\x18\a \x01(\v2\x11.AppRatingAuxDataR\aauxData*\xb8\x04\n" +
	"\rERatingAgency\x12\x1b\n" +
	"\x17k_ERatingAgency_Invalid\x10\x00\x12\x18\n" +
	"\x14k_ERatingAgency_ESRB\x10\x01\x12\x18\n" +
	"\x14k_ERatingAgency_PEGI\x10\x02\x12\x18\n" +
	"\x14k_ERatingAgency_BBFC\x10\x03\x12\x17\n" +
	"\x13k_ERatingAgency_USK\x10\x04\x12\x1b\n" +
	"\x17k_ERatingAgency_OFLC_AU\x10\x05\x12\x1b\n" +
	"\x17k_ERatingAgency_OFLC_NZ\x10\x06\x12\x18\n" +
	"\x14k_ERatingAgency_CERO\x10\a\x12\x18\n" +
	"\x14k_ERatingAgency_GRAC\x10\b\x12\x1a\n" +
	"\x16k_ERatingAgency_GMEDIA\x10\t\x12\x19\n" +
	"\x15k_ERatingAgency_DEJUS\x10\n" +
	"\x12\x18\n" +
	"\x14k_ERatingAgency_IMDA\x10\v\x12\x17\n" +
	"\x13k_ERatingAgency_FPB\x10\f\x12\x19\n" +
	"\x15k_ERatingAgency_TESRI\x10\r\x12\x18\n" +
	"\x14k_ERatingAgency_RARS\x10\x0e\x12\x19\n" +
	"\x15k_ERatingAgency_AGCOM\x10\x0f\x12\x18\n" +
	"\x14k_ERatingAgency_IGRS\x10\x10\x12!\n" +
	"\x1dk_ERatingAgency_Steam_Germany\x10\x11\x12#\n" +
	"\x1fk_ERatingAgency_Steam_Australia\x10\x12\x12\x19\n" +
	"\x15k_ERatingAgency_CADPA\x10\x13*u\n" +
	"\x10EAppRatingSource\x12\x1e\n" +
	"\x1ak_EAppRatingSource_Invalid\x10\x00\x12\x1f\n" +
	"\x1bk_EAppRatingSource_Official\x10\x01\x12 \n" +
	"\x1ck_EAppRatingSource_Generated\x10\x02B\x02H\x01"

var (
	file_steammessages_appratings_types_proto_rawDescOnce sync.Once
	file_steammessages_appratings_types_proto_rawDescData []byte
)

func file_steammessages_appratings_types_proto_rawDescGZIP() []byte {
	file_steammessages_appratings_types_proto_rawDescOnce.Do(func() {
		file_steammessages_appratings_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steammessages_appratings_types_proto_rawDesc), len(file_steammessages_appratings_types_proto_rawDesc)))
	})
	return file_steammessages_appratings_types_proto_rawDescData
}

var file_steammessages_appratings_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_steammessages_appratings_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_steammessages_appratings_types_proto_goTypes = []any{
	(ERatingAgency)(0),       // 0: ERatingAgency
	(EAppRatingSource)(0),    // 1: EAppRatingSource
	(*AppRatingAuxData)(nil), // 2: AppRatingAuxData
	(*AppRating)(nil),        // 3: AppRating
}
var file_steammessages_appratings_types_proto_depIdxs = []int32{
	0, // 0: AppRating.rating_agency:type_name -> ERatingAgency
	1, // 1: AppRating.source:type_name -> EAppRatingSource
	2, // 2: AppRating.aux_data:type_name -> AppRatingAuxData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_steammessages_appratings_types_proto_init() }
func file_steammessages_appratings_types_proto_init() {
	if File_steammessages_appratings_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_appratings_types_proto_rawDesc), len(file_steammessages_appratings_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_steammessages_appratings_types_proto_goTypes,
		DependencyIndexes: file_steammessages_appratings_types_proto_depIdxs,
		EnumInfos:         file_steammessages_appratings_types_proto_enumTypes,
		MessageInfos:      file_steammessages_appratings_types_proto_msgTypes,
	}.Build()
	File_steammessages_appratings_types_proto = out.File
	file_steammessages_appratings_types_proto_goTypes = nil
	file_steammessages_appratings_types_proto_depIdxs = nil
}
