// Code generated by protoc-gen-enums. DO NOT EDIT.

package steam

import (
	"net/url"
	"strconv"
)

// EncodeValues implements the query.Encoder interface for EChatRoomJoinState.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EChatRoomJoinState) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EChatRoomGroupRank.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EChatRoomGroupRank) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EChatRoomNotificationLevel.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EChatRoomNotificationLevel) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EChatRoomServerMessage.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EChatRoomServerMessage) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EChatRoomMessageReactionType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EChatRoomMessageReactionType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EChatRoomNotice.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EChatRoomNotice) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EChatRoomMemberStateChange.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EChatRoomMemberStateChange) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}
