// Code generated by protoc-gen-enums. DO NOT EDIT.

package steam

import (
	"net/url"
	"strconv"
)

// EncodeValues implements the query.Encoder interface for ERemoteClientPairWifiAPResult.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ERemoteClientPairWifiAPResult) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamingDongleFixResult.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamingDongleFixResult) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}
