// Code generated by protoc-gen-enums. DO NOT EDIT.

package steam

import (
	"net/url"
	"strconv"
)

// EncodeValues implements the query.Encoder interface for EStreamChannel.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamChannel) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamDiscoveryMessage.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamDiscoveryMessage) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamControlMessage.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamControlMessage) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamVersion.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamVersion) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamAudioCodec.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamAudioCodec) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamVideoCodec.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamVideoCodec) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamQualityPreference.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamQualityPreference) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamBitrate.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamBitrate) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamColorspace.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamColorspace) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamP2PScope.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamP2PScope) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamHostPlayAudioPreference.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamHostPlayAudioPreference) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamHostDisplaySetting.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamHostDisplaySetting) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamingDataType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamingDataType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamMouseButton.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamMouseButton) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamMouseWheelDirection.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamMouseWheelDirection) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamFramerateLimiter.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamFramerateLimiter) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamActivity.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamActivity) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ECaptureFailedReason.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ECaptureFailedReason) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamDataMessage.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamDataMessage) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EAudioFormat.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EAudioFormat) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EVideoFormat.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EVideoFormat) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamStatsMessage.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamStatsMessage) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamFrameEvent.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamFrameEvent) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamFrameResult.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamFrameResult) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EFrameAccumulatedStat.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EFrameAccumulatedStat) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ELogFileType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ELogFileType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamControllerConfigMsg.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamControllerConfigMsg) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}
