// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: webuimessages_audio.proto

package steam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CAudio_GetSupportedFeatures_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_GetSupportedFeatures_Request) Reset() {
	*x = CAudio_GetSupportedFeatures_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_GetSupportedFeatures_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_GetSupportedFeatures_Request) ProtoMessage() {}

func (x *CAudio_GetSupportedFeatures_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_GetSupportedFeatures_Request.ProtoReflect.Descriptor instead.
func (*CAudio_GetSupportedFeatures_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{0}
}

type CAudio_GetSupportedFeatures_Response struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	MonoDownmix              *bool                  `protobuf:"varint,1,opt,name=mono_downmix,json=monoDownmix" json:"mono_downmix,omitempty"`
	UseBluetoothForMic       *bool                  `protobuf:"varint,2,opt,name=use_bluetooth_for_mic,json=useBluetoothForMic" json:"use_bluetooth_for_mic,omitempty"`
	ResetConfig              *bool                  `protobuf:"varint,3,opt,name=reset_config,json=resetConfig" json:"reset_config,omitempty"`
	BluetoothAudioPreference *bool                  `protobuf:"varint,4,opt,name=bluetooth_audio_preference,json=bluetoothAudioPreference" json:"bluetooth_audio_preference,omitempty"`
	Spatialize               *bool                  `protobuf:"varint,5,opt,name=spatialize" json:"spatialize,omitempty"`
	SpatializeSurround       *bool                  `protobuf:"varint,6,opt,name=spatialize_surround,json=spatializeSurround" json:"spatialize_surround,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CAudio_GetSupportedFeatures_Response) Reset() {
	*x = CAudio_GetSupportedFeatures_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_GetSupportedFeatures_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_GetSupportedFeatures_Response) ProtoMessage() {}

func (x *CAudio_GetSupportedFeatures_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_GetSupportedFeatures_Response.ProtoReflect.Descriptor instead.
func (*CAudio_GetSupportedFeatures_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{1}
}

func (x *CAudio_GetSupportedFeatures_Response) GetMonoDownmix() bool {
	if x != nil && x.MonoDownmix != nil {
		return *x.MonoDownmix
	}
	return false
}

func (x *CAudio_GetSupportedFeatures_Response) GetUseBluetoothForMic() bool {
	if x != nil && x.UseBluetoothForMic != nil {
		return *x.UseBluetoothForMic
	}
	return false
}

func (x *CAudio_GetSupportedFeatures_Response) GetResetConfig() bool {
	if x != nil && x.ResetConfig != nil {
		return *x.ResetConfig
	}
	return false
}

func (x *CAudio_GetSupportedFeatures_Response) GetBluetoothAudioPreference() bool {
	if x != nil && x.BluetoothAudioPreference != nil {
		return *x.BluetoothAudioPreference
	}
	return false
}

func (x *CAudio_GetSupportedFeatures_Response) GetSpatialize() bool {
	if x != nil && x.Spatialize != nil {
		return *x.Spatialize
	}
	return false
}

func (x *CAudio_GetSupportedFeatures_Response) GetSpatializeSurround() bool {
	if x != nil && x.SpatializeSurround != nil {
		return *x.SpatializeSurround
	}
	return false
}

type CAudio_GetMonoDownmixEnabled_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_GetMonoDownmixEnabled_Request) Reset() {
	*x = CAudio_GetMonoDownmixEnabled_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_GetMonoDownmixEnabled_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_GetMonoDownmixEnabled_Request) ProtoMessage() {}

func (x *CAudio_GetMonoDownmixEnabled_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_GetMonoDownmixEnabled_Request.ProtoReflect.Descriptor instead.
func (*CAudio_GetMonoDownmixEnabled_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{2}
}

type CAudio_GetMonoDownmixEnabled_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_GetMonoDownmixEnabled_Response) Reset() {
	*x = CAudio_GetMonoDownmixEnabled_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_GetMonoDownmixEnabled_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_GetMonoDownmixEnabled_Response) ProtoMessage() {}

func (x *CAudio_GetMonoDownmixEnabled_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_GetMonoDownmixEnabled_Response.ProtoReflect.Descriptor instead.
func (*CAudio_GetMonoDownmixEnabled_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{3}
}

func (x *CAudio_GetMonoDownmixEnabled_Response) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type CAudio_SetMonoDownmixEnabled_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_SetMonoDownmixEnabled_Request) Reset() {
	*x = CAudio_SetMonoDownmixEnabled_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_SetMonoDownmixEnabled_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_SetMonoDownmixEnabled_Request) ProtoMessage() {}

func (x *CAudio_SetMonoDownmixEnabled_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_SetMonoDownmixEnabled_Request.ProtoReflect.Descriptor instead.
func (*CAudio_SetMonoDownmixEnabled_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{4}
}

func (x *CAudio_SetMonoDownmixEnabled_Request) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type CAudio_SetMonoDownmixEnabled_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_SetMonoDownmixEnabled_Response) Reset() {
	*x = CAudio_SetMonoDownmixEnabled_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_SetMonoDownmixEnabled_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_SetMonoDownmixEnabled_Response) ProtoMessage() {}

func (x *CAudio_SetMonoDownmixEnabled_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_SetMonoDownmixEnabled_Response.ProtoReflect.Descriptor instead.
func (*CAudio_SetMonoDownmixEnabled_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{5}
}

type CAudio_GetUseBluetoothForMic_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_GetUseBluetoothForMic_Request) Reset() {
	*x = CAudio_GetUseBluetoothForMic_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_GetUseBluetoothForMic_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_GetUseBluetoothForMic_Request) ProtoMessage() {}

func (x *CAudio_GetUseBluetoothForMic_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_GetUseBluetoothForMic_Request.ProtoReflect.Descriptor instead.
func (*CAudio_GetUseBluetoothForMic_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{6}
}

type CAudio_GetUseBluetoothForMic_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_GetUseBluetoothForMic_Response) Reset() {
	*x = CAudio_GetUseBluetoothForMic_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_GetUseBluetoothForMic_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_GetUseBluetoothForMic_Response) ProtoMessage() {}

func (x *CAudio_GetUseBluetoothForMic_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_GetUseBluetoothForMic_Response.ProtoReflect.Descriptor instead.
func (*CAudio_GetUseBluetoothForMic_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{7}
}

func (x *CAudio_GetUseBluetoothForMic_Response) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type CAudio_SetUseBluetoothForMic_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_SetUseBluetoothForMic_Request) Reset() {
	*x = CAudio_SetUseBluetoothForMic_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_SetUseBluetoothForMic_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_SetUseBluetoothForMic_Request) ProtoMessage() {}

func (x *CAudio_SetUseBluetoothForMic_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_SetUseBluetoothForMic_Request.ProtoReflect.Descriptor instead.
func (*CAudio_SetUseBluetoothForMic_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{8}
}

func (x *CAudio_SetUseBluetoothForMic_Request) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type CAudio_SetUseBluetoothForMic_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_SetUseBluetoothForMic_Response) Reset() {
	*x = CAudio_SetUseBluetoothForMic_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_SetUseBluetoothForMic_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_SetUseBluetoothForMic_Response) ProtoMessage() {}

func (x *CAudio_SetUseBluetoothForMic_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_SetUseBluetoothForMic_Response.ProtoReflect.Descriptor instead.
func (*CAudio_SetUseBluetoothForMic_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{9}
}

type CAudio_GetBluetoothAudioPreference_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_GetBluetoothAudioPreference_Request) Reset() {
	*x = CAudio_GetBluetoothAudioPreference_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_GetBluetoothAudioPreference_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_GetBluetoothAudioPreference_Request) ProtoMessage() {}

func (x *CAudio_GetBluetoothAudioPreference_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_GetBluetoothAudioPreference_Request.ProtoReflect.Descriptor instead.
func (*CAudio_GetBluetoothAudioPreference_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{10}
}

type CAudio_GetBluetoothAudioPreference_Response struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Preference    *EBluetoothAudioPreference `protobuf:"varint,1,opt,name=preference,enum=EBluetoothAudioPreference,def=0" json:"preference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CAudio_GetBluetoothAudioPreference_Response fields.
const (
	Default_CAudio_GetBluetoothAudioPreference_Response_Preference = EBluetoothAudioPreference_k_EBluetoothAudioPreference_Quality
)

func (x *CAudio_GetBluetoothAudioPreference_Response) Reset() {
	*x = CAudio_GetBluetoothAudioPreference_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_GetBluetoothAudioPreference_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_GetBluetoothAudioPreference_Response) ProtoMessage() {}

func (x *CAudio_GetBluetoothAudioPreference_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_GetBluetoothAudioPreference_Response.ProtoReflect.Descriptor instead.
func (*CAudio_GetBluetoothAudioPreference_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{11}
}

func (x *CAudio_GetBluetoothAudioPreference_Response) GetPreference() EBluetoothAudioPreference {
	if x != nil && x.Preference != nil {
		return *x.Preference
	}
	return Default_CAudio_GetBluetoothAudioPreference_Response_Preference
}

type CAudio_SetBluetoothAudioPreference_Request struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Preference    *EBluetoothAudioPreference `protobuf:"varint,1,opt,name=preference,enum=EBluetoothAudioPreference,def=0" json:"preference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CAudio_SetBluetoothAudioPreference_Request fields.
const (
	Default_CAudio_SetBluetoothAudioPreference_Request_Preference = EBluetoothAudioPreference_k_EBluetoothAudioPreference_Quality
)

func (x *CAudio_SetBluetoothAudioPreference_Request) Reset() {
	*x = CAudio_SetBluetoothAudioPreference_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_SetBluetoothAudioPreference_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_SetBluetoothAudioPreference_Request) ProtoMessage() {}

func (x *CAudio_SetBluetoothAudioPreference_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_SetBluetoothAudioPreference_Request.ProtoReflect.Descriptor instead.
func (*CAudio_SetBluetoothAudioPreference_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{12}
}

func (x *CAudio_SetBluetoothAudioPreference_Request) GetPreference() EBluetoothAudioPreference {
	if x != nil && x.Preference != nil {
		return *x.Preference
	}
	return Default_CAudio_SetBluetoothAudioPreference_Request_Preference
}

type CAudio_SetBluetoothAudioPreference_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_SetBluetoothAudioPreference_Response) Reset() {
	*x = CAudio_SetBluetoothAudioPreference_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_SetBluetoothAudioPreference_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_SetBluetoothAudioPreference_Response) ProtoMessage() {}

func (x *CAudio_SetBluetoothAudioPreference_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_SetBluetoothAudioPreference_Response.ProtoReflect.Descriptor instead.
func (*CAudio_SetBluetoothAudioPreference_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{13}
}

type CAudio_SupportsHdmiCec_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinkId        *int32                 `protobuf:"varint,1,opt,name=sink_id,json=sinkId" json:"sink_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_SupportsHdmiCec_Request) Reset() {
	*x = CAudio_SupportsHdmiCec_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_SupportsHdmiCec_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_SupportsHdmiCec_Request) ProtoMessage() {}

func (x *CAudio_SupportsHdmiCec_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_SupportsHdmiCec_Request.ProtoReflect.Descriptor instead.
func (*CAudio_SupportsHdmiCec_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{14}
}

func (x *CAudio_SupportsHdmiCec_Request) GetSinkId() int32 {
	if x != nil && x.SinkId != nil {
		return *x.SinkId
	}
	return 0
}

type CAudio_SupportsHdmiCec_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_SupportsHdmiCec_Response) Reset() {
	*x = CAudio_SupportsHdmiCec_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_SupportsHdmiCec_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_SupportsHdmiCec_Response) ProtoMessage() {}

func (x *CAudio_SupportsHdmiCec_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_SupportsHdmiCec_Response.ProtoReflect.Descriptor instead.
func (*CAudio_SupportsHdmiCec_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{15}
}

func (x *CAudio_SupportsHdmiCec_Response) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type CAudio_GetHdmiCecEnabled_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinkId        *int32                 `protobuf:"varint,1,opt,name=sink_id,json=sinkId" json:"sink_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_GetHdmiCecEnabled_Request) Reset() {
	*x = CAudio_GetHdmiCecEnabled_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_GetHdmiCecEnabled_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_GetHdmiCecEnabled_Request) ProtoMessage() {}

func (x *CAudio_GetHdmiCecEnabled_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_GetHdmiCecEnabled_Request.ProtoReflect.Descriptor instead.
func (*CAudio_GetHdmiCecEnabled_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{16}
}

func (x *CAudio_GetHdmiCecEnabled_Request) GetSinkId() int32 {
	if x != nil && x.SinkId != nil {
		return *x.SinkId
	}
	return 0
}

type CAudio_GetHdmiCecEnabled_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_GetHdmiCecEnabled_Response) Reset() {
	*x = CAudio_GetHdmiCecEnabled_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_GetHdmiCecEnabled_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_GetHdmiCecEnabled_Response) ProtoMessage() {}

func (x *CAudio_GetHdmiCecEnabled_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_GetHdmiCecEnabled_Response.ProtoReflect.Descriptor instead.
func (*CAudio_GetHdmiCecEnabled_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{17}
}

func (x *CAudio_GetHdmiCecEnabled_Response) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type CAudio_GetHdmiCecActive_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinkId        *int32                 `protobuf:"varint,1,opt,name=sink_id,json=sinkId" json:"sink_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_GetHdmiCecActive_Request) Reset() {
	*x = CAudio_GetHdmiCecActive_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_GetHdmiCecActive_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_GetHdmiCecActive_Request) ProtoMessage() {}

func (x *CAudio_GetHdmiCecActive_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_GetHdmiCecActive_Request.ProtoReflect.Descriptor instead.
func (*CAudio_GetHdmiCecActive_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{18}
}

func (x *CAudio_GetHdmiCecActive_Request) GetSinkId() int32 {
	if x != nil && x.SinkId != nil {
		return *x.SinkId
	}
	return 0
}

type CAudio_GetHdmiCecActive_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        *bool                  `protobuf:"varint,1,opt,name=active" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_GetHdmiCecActive_Response) Reset() {
	*x = CAudio_GetHdmiCecActive_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_GetHdmiCecActive_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_GetHdmiCecActive_Response) ProtoMessage() {}

func (x *CAudio_GetHdmiCecActive_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_GetHdmiCecActive_Response.ProtoReflect.Descriptor instead.
func (*CAudio_GetHdmiCecActive_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{19}
}

func (x *CAudio_GetHdmiCecActive_Response) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

type CAudio_SetHdmiCecEnabled_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinkId        *int32                 `protobuf:"varint,1,opt,name=sink_id,json=sinkId" json:"sink_id,omitempty"`
	Enabled       *bool                  `protobuf:"varint,2,opt,name=enabled" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_SetHdmiCecEnabled_Request) Reset() {
	*x = CAudio_SetHdmiCecEnabled_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_SetHdmiCecEnabled_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_SetHdmiCecEnabled_Request) ProtoMessage() {}

func (x *CAudio_SetHdmiCecEnabled_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_SetHdmiCecEnabled_Request.ProtoReflect.Descriptor instead.
func (*CAudio_SetHdmiCecEnabled_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{20}
}

func (x *CAudio_SetHdmiCecEnabled_Request) GetSinkId() int32 {
	if x != nil && x.SinkId != nil {
		return *x.SinkId
	}
	return 0
}

func (x *CAudio_SetHdmiCecEnabled_Request) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type CAudio_SetHdmiCecEnabled_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_SetHdmiCecEnabled_Response) Reset() {
	*x = CAudio_SetHdmiCecEnabled_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_SetHdmiCecEnabled_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_SetHdmiCecEnabled_Response) ProtoMessage() {}

func (x *CAudio_SetHdmiCecEnabled_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_SetHdmiCecEnabled_Response.ProtoReflect.Descriptor instead.
func (*CAudio_SetHdmiCecEnabled_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{21}
}

type CAudio_SendHdmiCecVolume_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinkId        *int32                 `protobuf:"varint,1,opt,name=sink_id,json=sinkId" json:"sink_id,omitempty"`
	Up            *bool                  `protobuf:"varint,2,opt,name=up" json:"up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_SendHdmiCecVolume_Request) Reset() {
	*x = CAudio_SendHdmiCecVolume_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_SendHdmiCecVolume_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_SendHdmiCecVolume_Request) ProtoMessage() {}

func (x *CAudio_SendHdmiCecVolume_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_SendHdmiCecVolume_Request.ProtoReflect.Descriptor instead.
func (*CAudio_SendHdmiCecVolume_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{22}
}

func (x *CAudio_SendHdmiCecVolume_Request) GetSinkId() int32 {
	if x != nil && x.SinkId != nil {
		return *x.SinkId
	}
	return 0
}

func (x *CAudio_SendHdmiCecVolume_Request) GetUp() bool {
	if x != nil && x.Up != nil {
		return *x.Up
	}
	return false
}

type CAudio_SendHdmiCecVolume_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_SendHdmiCecVolume_Response) Reset() {
	*x = CAudio_SendHdmiCecVolume_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_SendHdmiCecVolume_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_SendHdmiCecVolume_Response) ProtoMessage() {}

func (x *CAudio_SendHdmiCecVolume_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_SendHdmiCecVolume_Response.ProtoReflect.Descriptor instead.
func (*CAudio_SendHdmiCecVolume_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{23}
}

type CAudio_ToggleHdmiCecMute_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinkId        *int32                 `protobuf:"varint,1,opt,name=sink_id,json=sinkId" json:"sink_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_ToggleHdmiCecMute_Request) Reset() {
	*x = CAudio_ToggleHdmiCecMute_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_ToggleHdmiCecMute_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_ToggleHdmiCecMute_Request) ProtoMessage() {}

func (x *CAudio_ToggleHdmiCecMute_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_ToggleHdmiCecMute_Request.ProtoReflect.Descriptor instead.
func (*CAudio_ToggleHdmiCecMute_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{24}
}

func (x *CAudio_ToggleHdmiCecMute_Request) GetSinkId() int32 {
	if x != nil && x.SinkId != nil {
		return *x.SinkId
	}
	return 0
}

type CAudio_ToggleHdmiCecMute_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_ToggleHdmiCecMute_Response) Reset() {
	*x = CAudio_ToggleHdmiCecMute_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_ToggleHdmiCecMute_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_ToggleHdmiCecMute_Response) ProtoMessage() {}

func (x *CAudio_ToggleHdmiCecMute_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_ToggleHdmiCecMute_Response.ProtoReflect.Descriptor instead.
func (*CAudio_ToggleHdmiCecMute_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{25}
}

type CAudio_ResetConfig_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_ResetConfig_Request) Reset() {
	*x = CAudio_ResetConfig_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_ResetConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_ResetConfig_Request) ProtoMessage() {}

func (x *CAudio_ResetConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_ResetConfig_Request.ProtoReflect.Descriptor instead.
func (*CAudio_ResetConfig_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{26}
}

type CAudio_ResetConfig_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_ResetConfig_Response) Reset() {
	*x = CAudio_ResetConfig_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_ResetConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_ResetConfig_Response) ProtoMessage() {}

func (x *CAudio_ResetConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_ResetConfig_Response.ProtoReflect.Descriptor instead.
func (*CAudio_ResetConfig_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{27}
}

type CAudio_PlaySpeakerTestOnChannel_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelNum    *int32                 `protobuf:"varint,1,opt,name=channel_num,json=channelNum" json:"channel_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_PlaySpeakerTestOnChannel_Request) Reset() {
	*x = CAudio_PlaySpeakerTestOnChannel_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_PlaySpeakerTestOnChannel_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_PlaySpeakerTestOnChannel_Request) ProtoMessage() {}

func (x *CAudio_PlaySpeakerTestOnChannel_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_PlaySpeakerTestOnChannel_Request.ProtoReflect.Descriptor instead.
func (*CAudio_PlaySpeakerTestOnChannel_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{28}
}

func (x *CAudio_PlaySpeakerTestOnChannel_Request) GetChannelNum() int32 {
	if x != nil && x.ChannelNum != nil {
		return *x.ChannelNum
	}
	return 0
}

type CAudio_PlaySpeakerTestOnChannel_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_PlaySpeakerTestOnChannel_Response) Reset() {
	*x = CAudio_PlaySpeakerTestOnChannel_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_PlaySpeakerTestOnChannel_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_PlaySpeakerTestOnChannel_Response) ProtoMessage() {}

func (x *CAudio_PlaySpeakerTestOnChannel_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_PlaySpeakerTestOnChannel_Response.ProtoReflect.Descriptor instead.
func (*CAudio_PlaySpeakerTestOnChannel_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{29}
}

func (x *CAudio_PlaySpeakerTestOnChannel_Response) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

type CAudio_SetSpeakerConfiguration_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinkId        *int32                 `protobuf:"varint,1,opt,name=sink_id,json=sinkId" json:"sink_id,omitempty"`
	Config        *ESpeakerConfiguration `protobuf:"varint,2,opt,name=config,enum=ESpeakerConfiguration,def=0" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CAudio_SetSpeakerConfiguration_Request fields.
const (
	Default_CAudio_SetSpeakerConfiguration_Request_Config = ESpeakerConfiguration_k_ESpeakerConfiguration_Other
)

func (x *CAudio_SetSpeakerConfiguration_Request) Reset() {
	*x = CAudio_SetSpeakerConfiguration_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_SetSpeakerConfiguration_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_SetSpeakerConfiguration_Request) ProtoMessage() {}

func (x *CAudio_SetSpeakerConfiguration_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_SetSpeakerConfiguration_Request.ProtoReflect.Descriptor instead.
func (*CAudio_SetSpeakerConfiguration_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{30}
}

func (x *CAudio_SetSpeakerConfiguration_Request) GetSinkId() int32 {
	if x != nil && x.SinkId != nil {
		return *x.SinkId
	}
	return 0
}

func (x *CAudio_SetSpeakerConfiguration_Request) GetConfig() ESpeakerConfiguration {
	if x != nil && x.Config != nil {
		return *x.Config
	}
	return Default_CAudio_SetSpeakerConfiguration_Request_Config
}

type CAudio_SetSpeakerConfiguration_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ESpeakerConfiguration `protobuf:"varint,1,opt,name=config,enum=ESpeakerConfiguration,def=0" json:"config,omitempty"`
	Channels      *int32                 `protobuf:"varint,2,opt,name=channels" json:"channels,omitempty"`
	Sdescription  *string                `protobuf:"bytes,3,opt,name=sdescription" json:"sdescription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CAudio_SetSpeakerConfiguration_Response fields.
const (
	Default_CAudio_SetSpeakerConfiguration_Response_Config = ESpeakerConfiguration_k_ESpeakerConfiguration_Other
)

func (x *CAudio_SetSpeakerConfiguration_Response) Reset() {
	*x = CAudio_SetSpeakerConfiguration_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_SetSpeakerConfiguration_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_SetSpeakerConfiguration_Response) ProtoMessage() {}

func (x *CAudio_SetSpeakerConfiguration_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_SetSpeakerConfiguration_Response.ProtoReflect.Descriptor instead.
func (*CAudio_SetSpeakerConfiguration_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{31}
}

func (x *CAudio_SetSpeakerConfiguration_Response) GetConfig() ESpeakerConfiguration {
	if x != nil && x.Config != nil {
		return *x.Config
	}
	return Default_CAudio_SetSpeakerConfiguration_Response_Config
}

func (x *CAudio_SetSpeakerConfiguration_Response) GetChannels() int32 {
	if x != nil && x.Channels != nil {
		return *x.Channels
	}
	return 0
}

func (x *CAudio_SetSpeakerConfiguration_Response) GetSdescription() string {
	if x != nil && x.Sdescription != nil {
		return *x.Sdescription
	}
	return ""
}

type CAudio_GetSpatializeEnabled_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_GetSpatializeEnabled_Request) Reset() {
	*x = CAudio_GetSpatializeEnabled_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_GetSpatializeEnabled_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_GetSpatializeEnabled_Request) ProtoMessage() {}

func (x *CAudio_GetSpatializeEnabled_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_GetSpatializeEnabled_Request.ProtoReflect.Descriptor instead.
func (*CAudio_GetSpatializeEnabled_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{32}
}

type CAudio_GetSpatializeEnabled_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_GetSpatializeEnabled_Response) Reset() {
	*x = CAudio_GetSpatializeEnabled_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_GetSpatializeEnabled_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_GetSpatializeEnabled_Response) ProtoMessage() {}

func (x *CAudio_GetSpatializeEnabled_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_GetSpatializeEnabled_Response.ProtoReflect.Descriptor instead.
func (*CAudio_GetSpatializeEnabled_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{33}
}

func (x *CAudio_GetSpatializeEnabled_Response) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type CAudio_SetSpatializeEnabled_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_SetSpatializeEnabled_Request) Reset() {
	*x = CAudio_SetSpatializeEnabled_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_SetSpatializeEnabled_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_SetSpatializeEnabled_Request) ProtoMessage() {}

func (x *CAudio_SetSpatializeEnabled_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_SetSpatializeEnabled_Request.ProtoReflect.Descriptor instead.
func (*CAudio_SetSpatializeEnabled_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{34}
}

func (x *CAudio_SetSpatializeEnabled_Request) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type CAudio_SetSpatializeEnabled_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_SetSpatializeEnabled_Response) Reset() {
	*x = CAudio_SetSpatializeEnabled_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_SetSpatializeEnabled_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_SetSpatializeEnabled_Response) ProtoMessage() {}

func (x *CAudio_SetSpatializeEnabled_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_SetSpatializeEnabled_Response.ProtoReflect.Descriptor instead.
func (*CAudio_SetSpatializeEnabled_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{35}
}

type CAudio_GetSpatializeSurroundEnabled_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_GetSpatializeSurroundEnabled_Request) Reset() {
	*x = CAudio_GetSpatializeSurroundEnabled_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_GetSpatializeSurroundEnabled_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_GetSpatializeSurroundEnabled_Request) ProtoMessage() {}

func (x *CAudio_GetSpatializeSurroundEnabled_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_GetSpatializeSurroundEnabled_Request.ProtoReflect.Descriptor instead.
func (*CAudio_GetSpatializeSurroundEnabled_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{36}
}

type CAudio_GetSpatializeSurroundEnabled_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_GetSpatializeSurroundEnabled_Response) Reset() {
	*x = CAudio_GetSpatializeSurroundEnabled_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_GetSpatializeSurroundEnabled_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_GetSpatializeSurroundEnabled_Response) ProtoMessage() {}

func (x *CAudio_GetSpatializeSurroundEnabled_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_GetSpatializeSurroundEnabled_Response.ProtoReflect.Descriptor instead.
func (*CAudio_GetSpatializeSurroundEnabled_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{37}
}

func (x *CAudio_GetSpatializeSurroundEnabled_Response) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type CAudio_SetSpatializeSurroundEnabled_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_SetSpatializeSurroundEnabled_Request) Reset() {
	*x = CAudio_SetSpatializeSurroundEnabled_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_SetSpatializeSurroundEnabled_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_SetSpatializeSurroundEnabled_Request) ProtoMessage() {}

func (x *CAudio_SetSpatializeSurroundEnabled_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_SetSpatializeSurroundEnabled_Request.ProtoReflect.Descriptor instead.
func (*CAudio_SetSpatializeSurroundEnabled_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{38}
}

func (x *CAudio_SetSpatializeSurroundEnabled_Request) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type CAudio_SetSpatializeSurroundEnabled_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_SetSpatializeSurroundEnabled_Response) Reset() {
	*x = CAudio_SetSpatializeSurroundEnabled_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_SetSpatializeSurroundEnabled_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_SetSpatializeSurroundEnabled_Response) ProtoMessage() {}

func (x *CAudio_SetSpatializeSurroundEnabled_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_SetSpatializeSurroundEnabled_Response.ProtoReflect.Descriptor instead.
func (*CAudio_SetSpatializeSurroundEnabled_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{39}
}

var File_webuimessages_audio_proto protoreflect.FileDescriptor

const file_webuimessages_audio_proto_rawDesc = "" +
	"\n" +
	"\x19webuimessages_audio.proto\x1a\x18steammessages_base.proto\x1a\x18webuimessages_base.proto\x1a\venums.proto\"%\n" +
	"#CAudio_GetSupportedFeatures_Request\"\xae\x02\n" +
	"$CAudio_GetSupportedFeatures_Response\x12!\n" +
	"\fmono_downmix\x18\x01 \x01(\bR\vmonoDownmix\x121\n" +
	"\x15use_bluetooth_for_mic\x18\x02 \x01(\bR\x12useBluetoothForMic\x12!\n" +
	"\freset_config\x18\x03 \x01(\bR\vresetConfig\x12<\n" +
	"\x1abluetooth_audio_preference\x18\x04 \x01(\bR\x18bluetoothAudioPreference\x12\x1e\n" +
	"\n" +
	"spatialize\x18\x05 \x01(\bR\n" +
	"spatialize\x12/\n" +
	"\x13spatialize_surround\x18\x06 \x01(\bR\x12spatializeSurround\"&\n" +
	"$CAudio_GetMonoDownmixEnabled_Request\"A\n" +
	"%CAudio_GetMonoDownmixEnabled_Response\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"@\n" +
	"$CAudio_SetMonoDownmixEnabled_Request\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"'\n" +
	"%CAudio_SetMonoDownmixEnabled_Response\"&\n" +
	"$CAudio_GetUseBluetoothForMic_Request\"A\n" +
	"%CAudio_GetUseBluetoothForMic_Response\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"@\n" +
	"$CAudio_SetUseBluetoothForMic_Request\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"'\n" +
	"%CAudio_SetUseBluetoothForMic_Response\",\n" +
	"*CAudio_GetBluetoothAudioPreference_Request\"\x8e\x01\n" +
	"+CAudio_GetBluetoothAudioPreference_Response\x12_\n" +
	"\n" +
	"preference\x18\x01 \x01(\x0e2\x1a.EBluetoothAudioPreference:#k_EBluetoothAudioPreference_QualityR\n" +
	"preference\"\x8d\x01\n" +
	"*CAudio_SetBluetoothAudioPreference_Request\x12_\n" +
	"\n" +
	"preference\x18\x01 \x01(\x0e2\x1a.EBluetoothAudioPreference:#k_EBluetoothAudioPreference_QualityR\n" +
	"preference\"-\n" +
	"+CAudio_SetBluetoothAudioPreference_Response\"9\n" +
	"\x1eCAudio_SupportsHdmiCec_Request\x12\x17\n" +
	"\asink_id\x18\x01 \x01(\x05R\x06sinkId\";\n" +
	"\x1fCAudio_SupportsHdmiCec_Response\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\";\n" +
	" CAudio_GetHdmiCecEnabled_Request\x12\x17\n" +
	"\asink_id\x18\x01 \x01(\x05R\x06sinkId\"=\n" +
	"!CAudio_GetHdmiCecEnabled_Response\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\":\n" +
	"\x1fCAudio_GetHdmiCecActive_Request\x12\x17\n" +
	"\asink_id\x18\x01 \x01(\x05R\x06sinkId\":\n" +
	" CAudio_GetHdmiCecActive_Response\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\"U\n" +
	" CAudio_SetHdmiCecEnabled_Request\x12\x17\n" +
	"\asink_id\x18\x01 \x01(\x05R\x06sinkId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"#\n" +
	"!CAudio_SetHdmiCecEnabled_Response\"K\n" +
	" CAudio_SendHdmiCecVolume_Request\x12\x17\n" +
	"\asink_id\x18\x01 \x01(\x05R\x06sinkId\x12\x0e\n" +
	"\x02up\x18\x02 \x01(\bR\x02up\"#\n" +
	"!CAudio_SendHdmiCecVolume_Response\";\n" +
	" CAudio_ToggleHdmiCecMute_Request\x12\x17\n" +
	"\asink_id\x18\x01 \x01(\x05R\x06sinkId\"#\n" +
	"!CAudio_ToggleHdmiCecMute_Response\"\x1c\n" +
	"\x1aCAudio_ResetConfig_Request\"\x1d\n" +
	"\x1bCAudio_ResetConfig_Response\"J\n" +
	"'CAudio_PlaySpeakerTestOnChannel_Request\x12\x1f\n" +
	"\vchannel_num\x18\x01 \x01(\x05R\n" +
	"channelNum\"D\n" +
	"(CAudio_PlaySpeakerTestOnChannel_Response\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x90\x01\n" +
	"&CAudio_SetSpeakerConfiguration_Request\x12\x17\n" +
	"\asink_id\x18\x01 \x01(\x05R\x06sinkId\x12M\n" +
	"\x06config\x18\x02 \x01(\x0e2\x16.ESpeakerConfiguration:\x1dk_ESpeakerConfiguration_OtherR\x06config\"\xb8\x01\n" +
	"'CAudio_SetSpeakerConfiguration_Response\x12M\n" +
	"\x06config\x18\x01 \x01(\x0e2\x16.ESpeakerConfiguration:\x1dk_ESpeakerConfiguration_OtherR\x06config\x12\x1a\n" +
	"\bchannels\x18\x02 \x01(\x05R\bchannels\x12\"\n" +
	"\fsdescription\x18\x03 \x01(\tR\fsdescription\"%\n" +
	"#CAudio_GetSpatializeEnabled_Request\"@\n" +
	"$CAudio_GetSpatializeEnabled_Response\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"?\n" +
	"#CAudio_SetSpatializeEnabled_Request\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"&\n" +
	"$CAudio_SetSpatializeEnabled_Response\"-\n" +
	"+CAudio_GetSpatializeSurroundEnabled_Request\"H\n" +
	",CAudio_GetSpatializeSurroundEnabled_Response\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"G\n" +
	"+CAudio_SetSpatializeSurroundEnabled_Request\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\".\n" +
	",CAudio_SetSpatializeSurroundEnabled_Response2\x92\x10\n" +
	"\x05Audio\x12c\n" +
	"\x14GetSupportedFeatures\x12$.CAudio_GetSupportedFeatures_Request\x1a%.CAudio_GetSupportedFeatures_Response\x12f\n" +
	"\x15GetMonoDownmixEnabled\x12%.CAudio_GetMonoDownmixEnabled_Request\x1a&.CAudio_GetMonoDownmixEnabled_Response\x12f\n" +
	"\x15SetMonoDownmixEnabled\x12%.CAudio_SetMonoDownmixEnabled_Request\x1a&.CAudio_SetMonoDownmixEnabled_Response\x12f\n" +
	"\x15GetUseBluetoothForMic\x12%.CAudio_GetUseBluetoothForMic_Request\x1a&.CAudio_GetUseBluetoothForMic_Response\x12f\n" +
	"\x15SetUseBluetoothForMic\x12%.CAudio_SetUseBluetoothForMic_Request\x1a&.CAudio_SetUseBluetoothForMic_Response\x12x\n" +
	"\x1bGetBluetoothAudioPreference\x12+.CAudio_GetBluetoothAudioPreference_Request\x1a,.CAudio_GetBluetoothAudioPreference_Response\x12x\n" +
	"\x1bSetBluetoothAudioPreference\x12+.CAudio_SetBluetoothAudioPreference_Request\x1a,.CAudio_SetBluetoothAudioPreference_Response\x12T\n" +
	"\x0fSupportsHdmiCec\x12\x1f.CAudio_SupportsHdmiCec_Request\x1a .CAudio_SupportsHdmiCec_Response\x12Z\n" +
	"\x11GetHdmiCecEnabled\x12!.CAudio_GetHdmiCecEnabled_Request\x1a\".CAudio_GetHdmiCecEnabled_Response\x12W\n" +
	"\x10GetHdmiCecActive\x12 .CAudio_GetHdmiCecActive_Request\x1a!.CAudio_GetHdmiCecActive_Response\x12Z\n" +
	"\x11SetHdmiCecEnabled\x12!.CAudio_SetHdmiCecEnabled_Request\x1a\".CAudio_SetHdmiCecEnabled_Response\x12Z\n" +
	"\x11SendHdmiCecVolume\x12!.CAudio_SendHdmiCecVolume_Request\x1a\".CAudio_SendHdmiCecVolume_Response\x12Z\n" +
	"\x11ToggleHdmiCecMute\x12!.CAudio_ToggleHdmiCecMute_Request\x1a\".CAudio_ToggleHdmiCecMute_Response\x12c\n" +
	"\x14GetSpatializeEnabled\x12$.CAudio_GetSpatializeEnabled_Request\x1a%.CAudio_GetSpatializeEnabled_Response\x12c\n" +
	"\x14SetSpatializeEnabled\x12$.CAudio_SetSpatializeEnabled_Request\x1a%.CAudio_SetSpatializeEnabled_Response\x12{\n" +
	"\x1cGetSpatializeSurroundEnabled\x12,.CAudio_GetSpatializeSurroundEnabled_Request\x1a-.CAudio_GetSpatializeSurroundEnabled_Response\x12{\n" +
	"\x1cSetSpatializeSurroundEnabled\x12,.CAudio_SetSpatializeSurroundEnabled_Request\x1a-.CAudio_SetSpatializeSurroundEnabled_Response\x12H\n" +
	"\vResetConfig\x12\x1b.CAudio_ResetConfig_Request\x1a\x1c.CAudio_ResetConfig_Response\x12o\n" +
	"\x18PlaySpeakerTestOnChannel\x12(.CAudio_PlaySpeakerTestOnChannel_Request\x1a).CAudio_PlaySpeakerTestOnChannel_Response\x12l\n" +
	"\x17SetSpeakerConfiguration\x12'.CAudio_SetSpeakerConfiguration_Request\x1a(.CAudio_SetSpeakerConfiguration_Response\x1a\x04\x80\x97\"\x01B\x05H\x01\x80\x01\x01"

var (
	file_webuimessages_audio_proto_rawDescOnce sync.Once
	file_webuimessages_audio_proto_rawDescData []byte
)

func file_webuimessages_audio_proto_rawDescGZIP() []byte {
	file_webuimessages_audio_proto_rawDescOnce.Do(func() {
		file_webuimessages_audio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webuimessages_audio_proto_rawDesc), len(file_webuimessages_audio_proto_rawDesc)))
	})
	return file_webuimessages_audio_proto_rawDescData
}

var file_webuimessages_audio_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_webuimessages_audio_proto_goTypes = []any{
	(*CAudio_GetSupportedFeatures_Request)(nil),          // 0: CAudio_GetSupportedFeatures_Request
	(*CAudio_GetSupportedFeatures_Response)(nil),         // 1: CAudio_GetSupportedFeatures_Response
	(*CAudio_GetMonoDownmixEnabled_Request)(nil),         // 2: CAudio_GetMonoDownmixEnabled_Request
	(*CAudio_GetMonoDownmixEnabled_Response)(nil),        // 3: CAudio_GetMonoDownmixEnabled_Response
	(*CAudio_SetMonoDownmixEnabled_Request)(nil),         // 4: CAudio_SetMonoDownmixEnabled_Request
	(*CAudio_SetMonoDownmixEnabled_Response)(nil),        // 5: CAudio_SetMonoDownmixEnabled_Response
	(*CAudio_GetUseBluetoothForMic_Request)(nil),         // 6: CAudio_GetUseBluetoothForMic_Request
	(*CAudio_GetUseBluetoothForMic_Response)(nil),        // 7: CAudio_GetUseBluetoothForMic_Response
	(*CAudio_SetUseBluetoothForMic_Request)(nil),         // 8: CAudio_SetUseBluetoothForMic_Request
	(*CAudio_SetUseBluetoothForMic_Response)(nil),        // 9: CAudio_SetUseBluetoothForMic_Response
	(*CAudio_GetBluetoothAudioPreference_Request)(nil),   // 10: CAudio_GetBluetoothAudioPreference_Request
	(*CAudio_GetBluetoothAudioPreference_Response)(nil),  // 11: CAudio_GetBluetoothAudioPreference_Response
	(*CAudio_SetBluetoothAudioPreference_Request)(nil),   // 12: CAudio_SetBluetoothAudioPreference_Request
	(*CAudio_SetBluetoothAudioPreference_Response)(nil),  // 13: CAudio_SetBluetoothAudioPreference_Response
	(*CAudio_SupportsHdmiCec_Request)(nil),               // 14: CAudio_SupportsHdmiCec_Request
	(*CAudio_SupportsHdmiCec_Response)(nil),              // 15: CAudio_SupportsHdmiCec_Response
	(*CAudio_GetHdmiCecEnabled_Request)(nil),             // 16: CAudio_GetHdmiCecEnabled_Request
	(*CAudio_GetHdmiCecEnabled_Response)(nil),            // 17: CAudio_GetHdmiCecEnabled_Response
	(*CAudio_GetHdmiCecActive_Request)(nil),              // 18: CAudio_GetHdmiCecActive_Request
	(*CAudio_GetHdmiCecActive_Response)(nil),             // 19: CAudio_GetHdmiCecActive_Response
	(*CAudio_SetHdmiCecEnabled_Request)(nil),             // 20: CAudio_SetHdmiCecEnabled_Request
	(*CAudio_SetHdmiCecEnabled_Response)(nil),            // 21: CAudio_SetHdmiCecEnabled_Response
	(*CAudio_SendHdmiCecVolume_Request)(nil),             // 22: CAudio_SendHdmiCecVolume_Request
	(*CAudio_SendHdmiCecVolume_Response)(nil),            // 23: CAudio_SendHdmiCecVolume_Response
	(*CAudio_ToggleHdmiCecMute_Request)(nil),             // 24: CAudio_ToggleHdmiCecMute_Request
	(*CAudio_ToggleHdmiCecMute_Response)(nil),            // 25: CAudio_ToggleHdmiCecMute_Response
	(*CAudio_ResetConfig_Request)(nil),                   // 26: CAudio_ResetConfig_Request
	(*CAudio_ResetConfig_Response)(nil),                  // 27: CAudio_ResetConfig_Response
	(*CAudio_PlaySpeakerTestOnChannel_Request)(nil),      // 28: CAudio_PlaySpeakerTestOnChannel_Request
	(*CAudio_PlaySpeakerTestOnChannel_Response)(nil),     // 29: CAudio_PlaySpeakerTestOnChannel_Response
	(*CAudio_SetSpeakerConfiguration_Request)(nil),       // 30: CAudio_SetSpeakerConfiguration_Request
	(*CAudio_SetSpeakerConfiguration_Response)(nil),      // 31: CAudio_SetSpeakerConfiguration_Response
	(*CAudio_GetSpatializeEnabled_Request)(nil),          // 32: CAudio_GetSpatializeEnabled_Request
	(*CAudio_GetSpatializeEnabled_Response)(nil),         // 33: CAudio_GetSpatializeEnabled_Response
	(*CAudio_SetSpatializeEnabled_Request)(nil),          // 34: CAudio_SetSpatializeEnabled_Request
	(*CAudio_SetSpatializeEnabled_Response)(nil),         // 35: CAudio_SetSpatializeEnabled_Response
	(*CAudio_GetSpatializeSurroundEnabled_Request)(nil),  // 36: CAudio_GetSpatializeSurroundEnabled_Request
	(*CAudio_GetSpatializeSurroundEnabled_Response)(nil), // 37: CAudio_GetSpatializeSurroundEnabled_Response
	(*CAudio_SetSpatializeSurroundEnabled_Request)(nil),  // 38: CAudio_SetSpatializeSurroundEnabled_Request
	(*CAudio_SetSpatializeSurroundEnabled_Response)(nil), // 39: CAudio_SetSpatializeSurroundEnabled_Response
	(EBluetoothAudioPreference)(0),                       // 40: EBluetoothAudioPreference
	(ESpeakerConfiguration)(0),                           // 41: ESpeakerConfiguration
}
var file_webuimessages_audio_proto_depIdxs = []int32{
	40, // 0: CAudio_GetBluetoothAudioPreference_Response.preference:type_name -> EBluetoothAudioPreference
	40, // 1: CAudio_SetBluetoothAudioPreference_Request.preference:type_name -> EBluetoothAudioPreference
	41, // 2: CAudio_SetSpeakerConfiguration_Request.config:type_name -> ESpeakerConfiguration
	41, // 3: CAudio_SetSpeakerConfiguration_Response.config:type_name -> ESpeakerConfiguration
	0,  // 4: Audio.GetSupportedFeatures:input_type -> CAudio_GetSupportedFeatures_Request
	2,  // 5: Audio.GetMonoDownmixEnabled:input_type -> CAudio_GetMonoDownmixEnabled_Request
	4,  // 6: Audio.SetMonoDownmixEnabled:input_type -> CAudio_SetMonoDownmixEnabled_Request
	6,  // 7: Audio.GetUseBluetoothForMic:input_type -> CAudio_GetUseBluetoothForMic_Request
	8,  // 8: Audio.SetUseBluetoothForMic:input_type -> CAudio_SetUseBluetoothForMic_Request
	10, // 9: Audio.GetBluetoothAudioPreference:input_type -> CAudio_GetBluetoothAudioPreference_Request
	12, // 10: Audio.SetBluetoothAudioPreference:input_type -> CAudio_SetBluetoothAudioPreference_Request
	14, // 11: Audio.SupportsHdmiCec:input_type -> CAudio_SupportsHdmiCec_Request
	16, // 12: Audio.GetHdmiCecEnabled:input_type -> CAudio_GetHdmiCecEnabled_Request
	18, // 13: Audio.GetHdmiCecActive:input_type -> CAudio_GetHdmiCecActive_Request
	20, // 14: Audio.SetHdmiCecEnabled:input_type -> CAudio_SetHdmiCecEnabled_Request
	22, // 15: Audio.SendHdmiCecVolume:input_type -> CAudio_SendHdmiCecVolume_Request
	24, // 16: Audio.ToggleHdmiCecMute:input_type -> CAudio_ToggleHdmiCecMute_Request
	32, // 17: Audio.GetSpatializeEnabled:input_type -> CAudio_GetSpatializeEnabled_Request
	34, // 18: Audio.SetSpatializeEnabled:input_type -> CAudio_SetSpatializeEnabled_Request
	36, // 19: Audio.GetSpatializeSurroundEnabled:input_type -> CAudio_GetSpatializeSurroundEnabled_Request
	38, // 20: Audio.SetSpatializeSurroundEnabled:input_type -> CAudio_SetSpatializeSurroundEnabled_Request
	26, // 21: Audio.ResetConfig:input_type -> CAudio_ResetConfig_Request
	28, // 22: Audio.PlaySpeakerTestOnChannel:input_type -> CAudio_PlaySpeakerTestOnChannel_Request
	30, // 23: Audio.SetSpeakerConfiguration:input_type -> CAudio_SetSpeakerConfiguration_Request
	1,  // 24: Audio.GetSupportedFeatures:output_type -> CAudio_GetSupportedFeatures_Response
	3,  // 25: Audio.GetMonoDownmixEnabled:output_type -> CAudio_GetMonoDownmixEnabled_Response
	5,  // 26: Audio.SetMonoDownmixEnabled:output_type -> CAudio_SetMonoDownmixEnabled_Response
	7,  // 27: Audio.GetUseBluetoothForMic:output_type -> CAudio_GetUseBluetoothForMic_Response
	9,  // 28: Audio.SetUseBluetoothForMic:output_type -> CAudio_SetUseBluetoothForMic_Response
	11, // 29: Audio.GetBluetoothAudioPreference:output_type -> CAudio_GetBluetoothAudioPreference_Response
	13, // 30: Audio.SetBluetoothAudioPreference:output_type -> CAudio_SetBluetoothAudioPreference_Response
	15, // 31: Audio.SupportsHdmiCec:output_type -> CAudio_SupportsHdmiCec_Response
	17, // 32: Audio.GetHdmiCecEnabled:output_type -> CAudio_GetHdmiCecEnabled_Response
	19, // 33: Audio.GetHdmiCecActive:output_type -> CAudio_GetHdmiCecActive_Response
	21, // 34: Audio.SetHdmiCecEnabled:output_type -> CAudio_SetHdmiCecEnabled_Response
	23, // 35: Audio.SendHdmiCecVolume:output_type -> CAudio_SendHdmiCecVolume_Response
	25, // 36: Audio.ToggleHdmiCecMute:output_type -> CAudio_ToggleHdmiCecMute_Response
	33, // 37: Audio.GetSpatializeEnabled:output_type -> CAudio_GetSpatializeEnabled_Response
	35, // 38: Audio.SetSpatializeEnabled:output_type -> CAudio_SetSpatializeEnabled_Response
	37, // 39: Audio.GetSpatializeSurroundEnabled:output_type -> CAudio_GetSpatializeSurroundEnabled_Response
	39, // 40: Audio.SetSpatializeSurroundEnabled:output_type -> CAudio_SetSpatializeSurroundEnabled_Response
	27, // 41: Audio.ResetConfig:output_type -> CAudio_ResetConfig_Response
	29, // 42: Audio.PlaySpeakerTestOnChannel:output_type -> CAudio_PlaySpeakerTestOnChannel_Response
	31, // 43: Audio.SetSpeakerConfiguration:output_type -> CAudio_SetSpeakerConfiguration_Response
	24, // [24:44] is the sub-list for method output_type
	4,  // [4:24] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_webuimessages_audio_proto_init() }
func file_webuimessages_audio_proto_init() {
	if File_webuimessages_audio_proto != nil {
		return
	}
	file_steammessages_base_proto_init()
	file_webuimessages_base_proto_init()
	file_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webuimessages_audio_proto_rawDesc), len(file_webuimessages_audio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webuimessages_audio_proto_goTypes,
		DependencyIndexes: file_webuimessages_audio_proto_depIdxs,
		MessageInfos:      file_webuimessages_audio_proto_msgTypes,
	}.Build()
	File_webuimessages_audio_proto = out.File
	file_webuimessages_audio_proto_goTypes = nil
	file_webuimessages_audio_proto_depIdxs = nil
}
