// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: webuimessages_compatmanager.proto

package steam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMsgCompatManagerTool struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DisplayName    *string                `protobuf:"bytes,2,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	IsDefault      *bool                  `protobuf:"varint,3,opt,name=is_default,json=isDefault" json:"is_default,omitempty"`
	IsActive       *bool                  `protobuf:"varint,4,opt,name=is_active,json=isActive" json:"is_active,omitempty"`
	IsLegacy       *bool                  `protobuf:"varint,5,opt,name=is_legacy,json=isLegacy" json:"is_legacy,omitempty"`
	IsIncompatible *bool                  `protobuf:"varint,6,opt,name=is_incompatible,json=isIncompatible" json:"is_incompatible,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CMsgCompatManagerTool) Reset() {
	*x = CMsgCompatManagerTool{}
	mi := &file_webuimessages_compatmanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgCompatManagerTool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgCompatManagerTool) ProtoMessage() {}

func (x *CMsgCompatManagerTool) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_compatmanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgCompatManagerTool.ProtoReflect.Descriptor instead.
func (*CMsgCompatManagerTool) Descriptor() ([]byte, []int) {
	return file_webuimessages_compatmanager_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgCompatManagerTool) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CMsgCompatManagerTool) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *CMsgCompatManagerTool) GetIsDefault() bool {
	if x != nil && x.IsDefault != nil {
		return *x.IsDefault
	}
	return false
}

func (x *CMsgCompatManagerTool) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *CMsgCompatManagerTool) GetIsLegacy() bool {
	if x != nil && x.IsLegacy != nil {
		return *x.IsLegacy
	}
	return false
}

func (x *CMsgCompatManagerTool) GetIsIncompatible() bool {
	if x != nil && x.IsIncompatible != nil {
		return *x.IsIncompatible
	}
	return false
}

type CMsgCompatManagerAlias struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Alias           *string                `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	DisplayName     *string                `protobuf:"bytes,2,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	CurrentToolName *string                `protobuf:"bytes,3,opt,name=current_tool_name,json=currentToolName" json:"current_tool_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CMsgCompatManagerAlias) Reset() {
	*x = CMsgCompatManagerAlias{}
	mi := &file_webuimessages_compatmanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgCompatManagerAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgCompatManagerAlias) ProtoMessage() {}

func (x *CMsgCompatManagerAlias) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_compatmanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgCompatManagerAlias.ProtoReflect.Descriptor instead.
func (*CMsgCompatManagerAlias) Descriptor() ([]byte, []int) {
	return file_webuimessages_compatmanager_proto_rawDescGZIP(), []int{1}
}

func (x *CMsgCompatManagerAlias) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

func (x *CMsgCompatManagerAlias) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *CMsgCompatManagerAlias) GetCurrentToolName() string {
	if x != nil && x.CurrentToolName != nil {
		return *x.CurrentToolName
	}
	return ""
}

type CCompatManager_GetCompatTools_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         *uint32                `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCompatManager_GetCompatTools_Request) Reset() {
	*x = CCompatManager_GetCompatTools_Request{}
	mi := &file_webuimessages_compatmanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCompatManager_GetCompatTools_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCompatManager_GetCompatTools_Request) ProtoMessage() {}

func (x *CCompatManager_GetCompatTools_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_compatmanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCompatManager_GetCompatTools_Request.ProtoReflect.Descriptor instead.
func (*CCompatManager_GetCompatTools_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_compatmanager_proto_rawDescGZIP(), []int{2}
}

func (x *CCompatManager_GetCompatTools_Request) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

type CCompatManager_GetCompatTools_Response struct {
	state                  protoimpl.MessageState    `protogen:"open.v1"`
	Tools                  []*CMsgCompatManagerTool  `protobuf:"bytes,1,rep,name=tools" json:"tools,omitempty"`
	Aliases                []*CMsgCompatManagerAlias `protobuf:"bytes,2,rep,name=aliases" json:"aliases,omitempty"`
	SelectedToolIdentifier *string                   `protobuf:"bytes,3,opt,name=selected_tool_identifier,json=selectedToolIdentifier" json:"selected_tool_identifier,omitempty"`
	DefaultToolIdentifier  *string                   `protobuf:"bytes,4,opt,name=default_tool_identifier,json=defaultToolIdentifier" json:"default_tool_identifier,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CCompatManager_GetCompatTools_Response) Reset() {
	*x = CCompatManager_GetCompatTools_Response{}
	mi := &file_webuimessages_compatmanager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCompatManager_GetCompatTools_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCompatManager_GetCompatTools_Response) ProtoMessage() {}

func (x *CCompatManager_GetCompatTools_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_compatmanager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCompatManager_GetCompatTools_Response.ProtoReflect.Descriptor instead.
func (*CCompatManager_GetCompatTools_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_compatmanager_proto_rawDescGZIP(), []int{3}
}

func (x *CCompatManager_GetCompatTools_Response) GetTools() []*CMsgCompatManagerTool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *CCompatManager_GetCompatTools_Response) GetAliases() []*CMsgCompatManagerAlias {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *CCompatManager_GetCompatTools_Response) GetSelectedToolIdentifier() string {
	if x != nil && x.SelectedToolIdentifier != nil {
		return *x.SelectedToolIdentifier
	}
	return ""
}

func (x *CCompatManager_GetCompatTools_Response) GetDefaultToolIdentifier() string {
	if x != nil && x.DefaultToolIdentifier != nil {
		return *x.DefaultToolIdentifier
	}
	return ""
}

type CCompatManager_SpecifyCompatTool_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         *uint32                `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	ToolName      *string                `protobuf:"bytes,2,opt,name=tool_name,json=toolName" json:"tool_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCompatManager_SpecifyCompatTool_Request) Reset() {
	*x = CCompatManager_SpecifyCompatTool_Request{}
	mi := &file_webuimessages_compatmanager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCompatManager_SpecifyCompatTool_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCompatManager_SpecifyCompatTool_Request) ProtoMessage() {}

func (x *CCompatManager_SpecifyCompatTool_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_compatmanager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCompatManager_SpecifyCompatTool_Request.ProtoReflect.Descriptor instead.
func (*CCompatManager_SpecifyCompatTool_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_compatmanager_proto_rawDescGZIP(), []int{4}
}

func (x *CCompatManager_SpecifyCompatTool_Request) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CCompatManager_SpecifyCompatTool_Request) GetToolName() string {
	if x != nil && x.ToolName != nil {
		return *x.ToolName
	}
	return ""
}

type CCompatManager_SpecifyCompatTool_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCompatManager_SpecifyCompatTool_Response) Reset() {
	*x = CCompatManager_SpecifyCompatTool_Response{}
	mi := &file_webuimessages_compatmanager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCompatManager_SpecifyCompatTool_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCompatManager_SpecifyCompatTool_Response) ProtoMessage() {}

func (x *CCompatManager_SpecifyCompatTool_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_compatmanager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCompatManager_SpecifyCompatTool_Response.ProtoReflect.Descriptor instead.
func (*CCompatManager_SpecifyCompatTool_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_compatmanager_proto_rawDescGZIP(), []int{5}
}

type CCompatManager_StateChanged_Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCompatManager_StateChanged_Notification) Reset() {
	*x = CCompatManager_StateChanged_Notification{}
	mi := &file_webuimessages_compatmanager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCompatManager_StateChanged_Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCompatManager_StateChanged_Notification) ProtoMessage() {}

func (x *CCompatManager_StateChanged_Notification) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_compatmanager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCompatManager_StateChanged_Notification.ProtoReflect.Descriptor instead.
func (*CCompatManager_StateChanged_Notification) Descriptor() ([]byte, []int) {
	return file_webuimessages_compatmanager_proto_rawDescGZIP(), []int{6}
}

var File_webuimessages_compatmanager_proto protoreflect.FileDescriptor

const file_webuimessages_compatmanager_proto_rawDesc = "" +
	"\n" +
	"!webuimessages_compatmanager.proto\x1a\venums.proto\x1a\x18steammessages_base.proto\x1a\x18webuimessages_base.proto\"\xd0\x01\n" +
	"\x15CMsgCompatManagerTool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"is_default\x18\x03 \x01(\bR\tisDefault\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12\x1b\n" +
	"\tis_legacy\x18\x05 \x01(\bR\bisLegacy\x12'\n" +
	"\x0fis_incompatible\x18\x06 \x01(\bR\x0eisIncompatible\"}\n" +
	"\x16CMsgCompatManagerAlias\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12*\n" +
	"\x11current_tool_name\x18\x03 \x01(\tR\x0fcurrentToolName\"=\n" +
	"%CCompatManager_GetCompatTools_Request\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\"\xfb\x01\n" +
	"&CCompatManager_GetCompatTools_Response\x12,\n" +
	"\x05tools\x18\x01 \x03(\v2\x16.CMsgCompatManagerToolR\x05tools\x121\n" +
	"\aaliases\x18\x02 \x03(\v2\x17.CMsgCompatManagerAliasR\aaliases\x128\n" +
	"\x18selected_tool_identifier\x18\x03 \x01(\tR\x16selectedToolIdentifier\x126\n" +
	"\x17default_tool_identifier\x18\x04 \x01(\tR\x15defaultToolIdentifier\"]\n" +
	"(CCompatManager_SpecifyCompatTool_Request\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\"+\n" +
	")CCompatManager_SpecifyCompatTool_Response\"*\n" +
	"(CCompatManager_StateChanged_Notification2\xb7\x02\n" +
	"\rCompatManager\x12a\n" +
	"\x0eGetCompatTools\x12&.CCompatManager_GetCompatTools_Request\x1a'.CCompatManager_GetCompatTools_Response\x12j\n" +
	"\x11SpecifyCompatTool\x12).CCompatManager_SpecifyCompatTool_Request\x1a*.CCompatManager_SpecifyCompatTool_Response\x12Q\n" +
	"\x12NotifyStateChanged\x12).CCompatManager_StateChanged_Notification\x1a\x10.WebUINoResponse\x1a\x04\x80\x97\"\x02B\x05H\x01\x80\x01\x01"

var (
	file_webuimessages_compatmanager_proto_rawDescOnce sync.Once
	file_webuimessages_compatmanager_proto_rawDescData []byte
)

func file_webuimessages_compatmanager_proto_rawDescGZIP() []byte {
	file_webuimessages_compatmanager_proto_rawDescOnce.Do(func() {
		file_webuimessages_compatmanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webuimessages_compatmanager_proto_rawDesc), len(file_webuimessages_compatmanager_proto_rawDesc)))
	})
	return file_webuimessages_compatmanager_proto_rawDescData
}

var file_webuimessages_compatmanager_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_webuimessages_compatmanager_proto_goTypes = []any{
	(*CMsgCompatManagerTool)(nil),                     // 0: CMsgCompatManagerTool
	(*CMsgCompatManagerAlias)(nil),                    // 1: CMsgCompatManagerAlias
	(*CCompatManager_GetCompatTools_Request)(nil),     // 2: CCompatManager_GetCompatTools_Request
	(*CCompatManager_GetCompatTools_Response)(nil),    // 3: CCompatManager_GetCompatTools_Response
	(*CCompatManager_SpecifyCompatTool_Request)(nil),  // 4: CCompatManager_SpecifyCompatTool_Request
	(*CCompatManager_SpecifyCompatTool_Response)(nil), // 5: CCompatManager_SpecifyCompatTool_Response
	(*CCompatManager_StateChanged_Notification)(nil),  // 6: CCompatManager_StateChanged_Notification
	(*WebUINoResponse)(nil),                           // 7: WebUINoResponse
}
var file_webuimessages_compatmanager_proto_depIdxs = []int32{
	0, // 0: CCompatManager_GetCompatTools_Response.tools:type_name -> CMsgCompatManagerTool
	1, // 1: CCompatManager_GetCompatTools_Response.aliases:type_name -> CMsgCompatManagerAlias
	2, // 2: CompatManager.GetCompatTools:input_type -> CCompatManager_GetCompatTools_Request
	4, // 3: CompatManager.SpecifyCompatTool:input_type -> CCompatManager_SpecifyCompatTool_Request
	6, // 4: CompatManager.NotifyStateChanged:input_type -> CCompatManager_StateChanged_Notification
	3, // 5: CompatManager.GetCompatTools:output_type -> CCompatManager_GetCompatTools_Response
	5, // 6: CompatManager.SpecifyCompatTool:output_type -> CCompatManager_SpecifyCompatTool_Response
	7, // 7: CompatManager.NotifyStateChanged:output_type -> WebUINoResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_webuimessages_compatmanager_proto_init() }
func file_webuimessages_compatmanager_proto_init() {
	if File_webuimessages_compatmanager_proto != nil {
		return
	}
	file_enums_proto_init()
	file_steammessages_base_proto_init()
	file_webuimessages_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webuimessages_compatmanager_proto_rawDesc), len(file_webuimessages_compatmanager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webuimessages_compatmanager_proto_goTypes,
		DependencyIndexes: file_webuimessages_compatmanager_proto_depIdxs,
		MessageInfos:      file_webuimessages_compatmanager_proto_msgTypes,
	}.Build()
	File_webuimessages_compatmanager_proto = out.File
	file_webuimessages_compatmanager_proto_goTypes = nil
	file_webuimessages_compatmanager_proto_depIdxs = nil
}
